# Como-Article Ground/Vehicle MVP

Spec: `docs/specs/0006-como-article-ground-vehicle-mvp.md`

This is the canonical full-shard workflow for the current project. It uses a Spark-native prefilter before the Python extraction UDF, then writes the gold candidate dataset and compact analysis CSVs.

```text
Bronze corpus segments
  -> native Spark rlike prefilter for curated GROUND como article
  -> Python UDF extraction only on plausible rows
  -> gold Parquet and WebApp-ready CSV outputs
```

In [1]:
import os
from pathlib import Path
import sys

def find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "src/tal_qual").exists():
            return candidate
        if (candidate / "work/src/tal_qual").exists():
            return candidate / "work"
    raise RuntimeError(f"Could not find repository root from {start}")


REPO_ROOT = find_repo_root(Path.cwd())
os.chdir(REPO_ROOT)
SRC_DIR = REPO_ROOT / "src"
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

REPO_ROOT

PosixPath('/home/jovyan/work')

In [2]:
import os
import tempfile
import zipfile

from pyspark.sql import SparkSession

SPARK_MASTER = os.environ.get("TAL_QUAL_SPARK_MASTER", "local[4]")
SPARK_PARALLELISM = os.environ.get("TAL_QUAL_SPARK_PARALLELISM", "4")
SPARK_SHUFFLE_PARTITIONS = os.environ.get("TAL_QUAL_SPARK_SHUFFLE_PARTITIONS", "4")

spark = (
    SparkSession.builder
    .master(SPARK_MASTER)
    .appName("tal-qual-como-article-ground-vehicle-optimized-mvp")
    .config("spark.default.parallelism", SPARK_PARALLELISM)
    .config("spark.sql.shuffle.partitions", SPARK_SHUFFLE_PARTITIONS)
    .config("spark.sql.files.maxPartitionBytes", str(256 * 1024 * 1024))
    .getOrCreate()
)
spark.sparkContext.setLogLevel("WARN")

package_zip = Path(tempfile.gettempdir()) / "tal_qual_src.zip"
with zipfile.ZipFile(package_zip, "w", compression=zipfile.ZIP_DEFLATED) as archive:
    for file_path in sorted((SRC_DIR / "tal_qual").rglob("*.py")):
        archive.write(file_path, file_path.relative_to(SRC_DIR))

spark.sparkContext.addPyFile(str(package_zip))
SPARK_MASTER, spark.version

('local[4]', '4.1.1')

In [3]:
from tal_qual.bronze import BRONZE_OUTPUT_PATH, RAW_CORPUS_INPUT, prepare_bronze_dataframe, write_bronze_parquet
from tal_qual.como_article_ground_vehicle import (
    COMO_ARTICLE_EXAMPLES_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_VEHICLE_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_VEHICLE_OUTPUT_PATH,
    COMO_ARTICLE_REVIEW_SAMPLE_OUTPUT_PATH,
    COMO_ARTICLE_VEHICLE_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_VEHICLE_GROUND_COUNTS_OUTPUT_PATH,
    como_article_examples_dataframe,
    como_article_ground_counts_dataframe,
    como_article_ground_vehicle_counts_dataframe,
    como_article_review_sample_dataframe,
    como_article_vehicle_counts_dataframe,
    como_article_vehicle_ground_counts_dataframe,
    prefilter_como_article_ground_vehicle_bronze_dataframe,
    prepare_como_article_ground_vehicle_dataframe,
    write_como_article_csv_outputs,
    write_como_article_ground_vehicle_parquet,
)

## Load Or Build Bronze

The extractor expects the bronze schema from notebook 02. If bronze output is absent, this notebook builds it from the configured raw shard.

In [4]:
bronze_path = REPO_ROOT / BRONZE_OUTPUT_PATH
raw_path = REPO_ROOT / RAW_CORPUS_INPUT

if bronze_path.exists():
    bronze_df = spark.read.parquet(str(bronze_path))
else:
    bronze_df = prepare_bronze_dataframe(spark, raw_path)
    write_bronze_parquet(bronze_df, bronze_path)

bronze_df.printSchema()

root
 |-- source_file: string (nullable = true)
 |-- original_line_id: long (nullable = true)
 |-- segment_id: integer (nullable = true)
 |-- text_original: string (nullable = true)
 |-- text_normalized: string (nullable = true)
 |-- match_text: string (nullable = true)

## Prefilter And Extract Spec-0006 Candidates

The native prefilter is intentionally broad but cheap. It reduces the number of rows sent through the Python UDF.

In [5]:
prefiltered_bronze_df = prefilter_como_article_ground_vehicle_bronze_dataframe(bronze_df).persist()
prefiltered_count = prefiltered_bronze_df.count()
print(f"Prefiltered bronze rows: {prefiltered_count:,}")

candidates_df = prepare_como_article_ground_vehicle_dataframe(prefiltered_bronze_df).persist()
candidate_count = candidates_df.count()
print(f"Spec-0006 candidates: {candidate_count:,}")
candidates_df

Prefiltered bronze rows: 333

/usr/local/spark/python/pyspark/sql/udf.py:134: UserWarning: Cannot infer the eval type from type hints.
  warnings.warn("Cannot infer the eval type from type hints. ", UserWarning)

Spec-0006 candidates: 204

DataFrame[candidate_id: string, source_file: string, original_line_id: bigint, segment_id: int, pattern_type: string, connector: string, connector_text: string, matched_text: string, candidate_full_text: string, text_before: string, tenor_text: string, tenor_lemma: string, tenor_confidence: string, ground_text: string, ground_lemma: string, ground_type: string, ground_source: string, vehicle_text: string, vehicle_lemma: string, vehicle_head: string, vehicle_head_lemma: string, vehicle_phrase_length_tokens: int, filter_label: string, reject_reason: string, confidence: double, needs_review: boolean, char_start: int, char_end: int, connector_start: int, connector_end: int, vehicle_start: int, vehicle_end: int]

In [6]:
candidates_df.printSchema()

root
 |-- candidate_id: string (nullable = true)
 |-- source_file: string (nullable = true)
 |-- original_line_id: long (nullable = true)
 |-- segment_id: integer (nullable = true)
 |-- pattern_type: string (nullable = true)
 |-- connector: string (nullable = true)
 |-- connector_text: string (nullable = true)
 |-- matched_text: string (nullable = true)
 |-- candidate_full_text: string (nullable = true)
 |-- text_before: string (nullable = true)
 |-- tenor_text: string (nullable = true)
 |-- tenor_lemma: string (nullable = true)
 |-- tenor_confidence: string (nullable = true)
 |-- ground_text: string (nullable = true)
 |-- ground_lemma: string (nullable = true)
 |-- ground_type: string (nullable = true)
 |-- ground_source: string (nullable = true)
 |-- vehicle_text: string (nullable = true)
 |-- vehicle_lemma: string (nullable = true)
 |-- vehicle_head: string (nullable = true)
 |-- vehicle_head_lemma: string (nullable = true)
 |-- vehicle_phrase_length_tokens: integer (nullable = true)
 |-- filter_label: string (nullable = true)
 |-- reject_reason: string (nullable = true)
 |-- confidence: double (nullable = true)
 |-- needs_review: boolean (nullable = true)
 |-- char_start: integer (nullable = true)
 |-- char_end: integer (nullable = true)
 |-- connector_start: integer (nullable = true)
 |-- connector_end: integer (nullable = true)
 |-- vehicle_start: integer (nullable = true)
 |-- vehicle_end: integer (nullable = true)

## Write Gold Dataset And Visualization CSVs

In [7]:
write_como_article_ground_vehicle_parquet(candidates_df, REPO_ROOT / COMO_ARTICLE_GROUND_VEHICLE_OUTPUT_PATH)
write_como_article_csv_outputs(
    candidates_df,
    ground_vehicle_counts_path=REPO_ROOT / COMO_ARTICLE_GROUND_VEHICLE_COUNTS_OUTPUT_PATH,
    vehicle_ground_counts_path=REPO_ROOT / COMO_ARTICLE_VEHICLE_GROUND_COUNTS_OUTPUT_PATH,
    ground_counts_path=REPO_ROOT / COMO_ARTICLE_GROUND_COUNTS_OUTPUT_PATH,
    vehicle_counts_path=REPO_ROOT / COMO_ARTICLE_VEHICLE_COUNTS_OUTPUT_PATH,
    examples_path=REPO_ROOT / COMO_ARTICLE_EXAMPLES_OUTPUT_PATH,
    review_sample_path=REPO_ROOT / COMO_ARTICLE_REVIEW_SAMPLE_OUTPUT_PATH,
)

## Inspect Visualization Tables

These displays use small materialized pandas tables for readability. The durable CSV outputs above remain the source of truth for downstream visualization work.

In [8]:
from pyspark.sql.functions import col

def display_table(spark_df, limit=30):
    display(spark_df.limit(limit).toPandas())

### Ground -> Vehicle Pairs

In [9]:
display_table(
    como_article_ground_vehicle_counts_dataframe(candidates_df).select(
        col("ground_lemma").alias("ground"),
        col("vehicle_head_lemma").alias("vehicle_head"),
        "count",
    ),
    limit=40,
)

       ground vehicle_head  count
0        cair         luva     49
1        cair        bomba     24
2       forte        touro      4
3    assentar         luva      3
4       caber         luva      3
5    encaixar         luva      3
6     flutuar    borboleta      3
7      rápido       flecha      3
8      rápido         raio      3
9        cair   verdadeiro      2
10       cego      morcego      2
11  trabalhar      empresa      2
12  trabalhar   verdadeiro      2
13       voar        avião      2
14     alegre   passarinho      1
15       alto        caixa      1
16       alto      estrela      1
17       alto          pau      1
18       alto      pássaro      1
19       alto        super      1
20      baixo        barco      1
21      baixo       espaço      1
22      baixo         pipa      1
23      baixo        prego      1
24  brilhante        caixa      1
25  brilhante          luz      1
26    brilhar       centro      1
27    brilhar   gigantesco      1
28    brilhar         joia      1
29    brilhar        noiva      1
30       cair        aluva      1
31       cair      baralho      1
32       cair   castelinho      1
33       cair      patinha      1
34       cair      patinho      1
35       cair         raio      1
36       cair      simples      1
37       cair       trouxa      1
38      calmo        bomba      1
39      cheio          ovo      1

### Vehicle -> Ground Pairs

In [10]:
display_table(
    como_article_vehicle_ground_counts_dataframe(candidates_df).select(
        col("vehicle_head_lemma").alias("vehicle_head"),
        col("ground_lemma").alias("ground"),
        "count",
    ),
    limit=40,
)

   vehicle_head     ground  count
0          luva       cair     49
1         bomba       cair     24
2         touro      forte      4
3     borboleta    flutuar      3
4        flecha     rápido      3
5          luva   assentar      3
6          luva      caber      3
7          luva   encaixar      3
8          raio     rápido      3
9         avião       voar      2
10      empresa  trabalhar      2
11      morcego       cego      2
12   verdadeiro       cair      2
13   verdadeiro  trabalhar      2
14    aldebarán     rápido      1
15     alimento       doce      1
16        aluva       cair      1
17     amistoso     correr      1
18      artista  trabalhar      1
19     ativista  trabalhar      1
20     bacalhau       seco      1
21         bala     correr      1
22         bala    pequeno      1
23         bala     rápido      1
24      baralho       cair      1
25        barco      baixo      1
26    bicicleta    pequeno      1
27   bolachanos       duro      1
28        bomba      calmo      1
29        caixa       alto      1
30        caixa  brilhante      1
31     caminhão     grande      1
32     carvalho      forte      1
33      carícia       leve      1
34   castelinho       cair      1
35       cavalo      forte      1
36       cavalo     grande      1
37       centro    brilhar      1
38          chá     quente      1
39       cidade       duro      1

### Ground Counts

In [11]:
display_table(como_article_ground_counts_dataframe(candidates_df), limit=40)

   ground_lemma  count
0          cair     83
1     trabalhar     15
2         forte     12
3        rápido      9
4        correr      6
5          duro      6
6        grande      6
7          voar      6
8          alto      5
9      encaixar      5
10        baixo      4
11      brilhar      4
12      pequeno      4
13         seco      4
14     assentar      3
15        caber      3
16      flutuar      3
17         leve      3
18    brilhante      2
19         cego      2
20        claro      2
21         doce      2
22       escuro      2
23       frágil      2
24        livre      2
25       pesado      2
26       quente      2
27       alegre      1
28        calmo      1
29        cheio      1
30       triste      1
31        vazio      1

### Vehicle Counts

In [12]:
display_table(como_article_vehicle_counts_dataframe(candidates_df), limit=40)

   vehicle_head_lemma  count
0                luva     58
1               bomba     25
2                raio      4
3               touro      4
4          verdadeiro      4
5                bala      3
6           borboleta      3
7              flecha      3
8               avião      2
9               caixa      2
10             cavalo      2
11              dente      2
12            empresa      2
13            morcego      2
14         passarinho      2
15              pedra      2
16              pluma      2
17            pássaro      2
18            simples      2
19          aldebarán      1
20           alimento      1
21              aluva      1
22           amistoso      1
23            artista      1
24           ativista      1
25           bacalhau      1
26            baralho      1
27              barco      1
28          bicicleta      1
29         bolachanos      1
30           caminhão      1
31           carvalho      1
32            carícia      1
33         castelinho      1
34             centro      1
35                chá      1
36             cidade      1
37          cientista      1
38              cinza      1
39             coelho      1

### Examples

In [13]:
display_table(
    como_article_examples_dataframe(candidates_df, limit=100).select(
        "ground_text",
        "connector_text",
        "vehicle_text",
        "tenor_text",
        "candidate_full_text",
    ),
    limit=50,
)

,ground_text,connector_text,vehicle_text,tenor_text,candidate_full_text
0,alegre,como um,passarinho,olhos e saltou da cama,"Ela abriu os olhos e saltou da cama, alegre co..."
1,alto,como uma,caixa,vamos sentar sobre algo mais,Para iniciar com tranqüilidade vamos sentar so...
2,alta,como uma,estrela,meu baço é tão curto,"gro vê-la, cego ser e não vê-la, eu preferira:..."
3,alta,como um,pau de sebo,A criada,"A criada, alta como um pau de sebo"
4,alto,como um,pássaro com asas de anjo,céu além das estrelas Voarei,"Voarei além do céu, além das estrelas Voarei a..."
5,alto,como um,super heroi,já sonhou que estava voando,Se você já sonhou que estava voando alto como ...
6,assenta,como uma,luva,esquerda a quem o futuro,"mundo tem lutado nasce da ideia de que ""o bem""..."
7,assenta,como uma,luva,seguramente um daqueles a quem,Álvaro Magalhães é seguramente um daqueles a q...
8,assenta,como uma,luva no dia de hoje,ver aqui há um que,"NA LISTA de livros que se pode ver [aqui], há ..."
9,baixo,como um,barco,um sofá dinamarquês longo e,empo eu supri minha sala com uma moderna répli...
10,baixo,como um,espaço de sala ou serviços,desnível usando o andar de,"ncia maior igual que 20m, é interessante aprov..."
11,baixo,como uma,pipa,ver a vida lá em,"olveu tentar descobrir como era, se não voar c..."
12,baixo,como um,prego saindo de alguma madeira,ele irá obter bateu para,Ouvi dizer que você não furar sua cabeça no Ja...
13,Brilhante,como uma,caixa de celofane âmbar,,Brilhante como uma caixa de celofane âmbar
14,Brilhantes,como uma,luz,JESUS Escrita em lindos cartões,"ações!E quando chega o Natal,Levo a história d..."
15,brilhava,como um,centro planetário,No meio da mesa,"No meio da mesa, brilhava como um centro plane..."
16,brilhar,como um,gigantesco arco-íris repetitivo,que o céu haveria de,Por que o céu haveria de brilhar como um gigan...
17,brilhar,como uma,joia,sucedida ainda assim continuará a,e apesar de todo o esforço não seja bem sucedi...
18,brilhar,como uma,noiva esplêndida e inesquecível,realmente lindos que farão você,Nesta categoria há modelos realmente lindos qu...
19,cabe,como uma,luva,repete como farsa ou tragédia,"renovada citação de Karl Marx - ""A história se..."
20,coube,como uma,luva,AVESTRUZ 4O arremate nesse caso,"MOELA DE AVESTRUZ 4O arremate, nesse caso, cou..."
21,cabe,como uma,luva,é o personagem que lhe,Chico Bondade é o personagem que lhe cabe como...
22,caiu,como um,aluva,tempinho para aperfeiçoar o idioma,"Ótimo texto, pra mim que pretendo ficar la um ..."
23,cair,como um,baralho de cartas,por interesses pessoais acabam por,"rio, quando são feitas com mentiras e movidas ..."
24,caiu,como uma,bomba,Essa noticia,Essa noticia caiu como uma bomba
25,cai,como uma,bomba,Na tarde,"Na tarde, cai como uma bomba"
26,caiu,como uma,bomba,a nomeação de Luiz Almir,"e mais emprega no RN e, uma das que gera mais ..."
27,caiu,como uma,bomba atômica nos meios políticos,A delação de Sérgio Machado,A delação de Sérgio Machado caiu como uma bomb...
28,caiu,como uma,bomba na cidade,Bacellar saúde e Francejane educação,"ria aos secretários (à época, Charles Bacellar..."
29,caiu,como uma,bomba no meio político e,Jornal Folha de São Paulo,"A notícia, divulgada, ontem, à tarde, pelo Jor..."
30,cai,como uma,bomba no Planalto,republicanas delação da Andrade Gutierrez,idente participou das tratativas nada republic...
31,caiu,como uma,bomba entre os ambientalistas,do Serviço Geológico do Brasil,A sugestão do Serviço Geológico do Brasil caiu...
32,caiu,como uma,bomba no meu cérebro,A frase,A frase caiu como uma bomba no meu cérebro
33,caiu,como uma,bomba,A mais recente pesquisa,……………A mais recente pesquisa caiu como uma bomba
34,caiu,como uma,bomba entre a gente,Isso,"""Isso caiu como uma bomba entre a gente"
35,cai,como uma,bomba,mas quando nos é comunicado,"»Pensamos que isto só acontece aos outros, mas..."
36,caiu,como uma,bomba no meio da comunidade,para júbilo e comemoração porém,O que poderia ter sido motivo para júbilo e co...
37,cairia,como uma,bomba para estas eleições,união de Ronaldo e Belmiro,A união de Ronaldo e Belmiro cairia como uma b...
38,caiu,como uma,bomba no Heriberto Hulse,com muuuito trabalho e raça,"que o Criciúma poderia perder pontos, conquist..."
39,caiu,como uma,bomba,eu poderia até dizer que,elo final de tarde que a Rádio Macau deu a not...
40,caiu,como uma,bomba sobre o Centro Administrativo,campanha Santa Catarina em Ação,"ra da Fazenda Pública, proibindo a veiculação ..."
41,caiu,como uma,bomba,A informação,A informação caiu como uma bomba
42,caiu,como uma,bomba,Aquela notícia me,Aquela notícia me caiu como uma bomba
43,caiu,como uma,bomba,Na época isso,"Na época, isso caiu como uma bomba"
44,caiu,como uma,bomba em Búzios,anos do Chiquinho da Educação,A notícia da inelegibilidade por 10 anos do Ch...
45,caiu,como uma,bomba sem trocadilhos,Na época a reportagem,"Na época, a reportagem caiu como uma bomba sem..."
46,caiu,como uma,bomba,A notícia,A notícia caiu como uma bomba
47,caiu,como uma,bomba no mercado,do terceiro trimestre da Petrobras,Petrobras: dias ruins O balanço do terceiro tr...
48,caiu,como um,castelinho de areia,casar e de repente tudo,"ada tava numa boa com ele, viajando , fazendo ..."
49,caiu,como uma,luva,diretoria o caso de Artur,"Para a diretoria, o caso de Artur caiu como um..."

### Review Sample

In [14]:
display_table(
    como_article_review_sample_dataframe(candidates_df, limit=100).select(
        "ground_type",
        "ground_text",
        "connector_text",
        "vehicle_text",
        "tenor_text",
        "confidence",
        "needs_review",
        "candidate_full_text",
    ),
    limit=50,
)

,ground_type,ground_text,connector_text,vehicle_text,tenor_text,confidence,needs_review,candidate_full_text
0,salient_verb,Flutuar,como uma,borboleta,,0.75,True,Flutuar como uma borboleta
1,quality_adjective,Forte,como um,touro e alfabetizada,,0.75,True,Forte como um touro e alfabetizada
2,quality_adjective,Livre,como um,táxi,,0.75,True,Livre como um táxi
3,quality_adjective,Rápida,como uma,flecha,,0.75,True,Rápida como uma flecha
4,quality_adjective,Calmo,Como Uma,Bomba,,0.75,True,Calmo Como Uma Bomba
5,salient_verb,Correu,como uma,bala para a pensão,,0.75,True,Correu como uma bala para a pensão
6,quality_adjective,Cego,como um,morcego,,0.75,True,Cego como um morcego
7,quality_adjective,Brilhante,como uma,caixa de celofane âmbar,,0.75,True,Brilhante como uma caixa de celofane âmbar
8,quality_adjective,baixo,como um,prego saindo de alguma madeira,ele irá obter bateu para,0.90,False,Ouvi dizer que você não furar sua cabeça no Ja...
9,salient_verb,caiu,como um,castelinho de areia,casar e de repente tudo,0.90,False,"ada tava numa boa com ele, viajando , fazendo ..."
10,salient_verb,cai,como uma,luva para o papel,interpretado por um sujeito que,0.90,False,"[…] mundial dos vinhos, é interpretado por um ..."
11,quality_adjective,fortes,como um,quintal de luxo,a miséria aproveitando nossos pontos,0.90,False,"e talvez seja: primeiro, combater a fome e a m..."
12,salient_verb,trabalhar,como um,artista de graffiti,de oitenta ele começou a,0.90,False,"Na década de oitenta, ele começou a trabalhar ..."
13,salient_verb,caiu,como uma,bomba atômica nos meios políticos,A delação de Sérgio Machado,0.90,False,A delação de Sérgio Machado caiu como uma bomb...
14,salient_verb,caiu,como um,verdadeiro tsunami em Hollywood,A sueca,0.90,False,A sueca caiu como um verdadeiro tsunami em Hol...
15,quality_adjective,pesado,como uma,fragata a menos,mais lógico que um vaso,0.90,False,tos mais atuais são de longuíssimo alcance ) e...
16,salient_verb,caiu,como uma,bomba na cidade,Bacellar saúde e Francejane educação,0.90,False,"ria aos secretários (à época, Charles Bacellar..."
17,salient_verb,caiu,como uma,bomba no meio político e,Jornal Folha de São Paulo,0.90,False,"A notícia, divulgada, ontem, à tarde, pelo Jor..."
18,salient_verb,correu,como um,possuído na chuva,o alemão da Toro Rosso,0.90,False,"Mais uma vez, o alemão da Toro Rosso correu co..."
19,salient_verb,cai,como uma,bomba no Planalto,republicanas delação da Andrade Gutierrez,0.90,False,idente participou das tratativas nada republic...
20,salient_verb,cai,como uma,luva no conceito de abnegação,Logo,0.90,False,"Logo, cai como uma luva no conceito de abnegação"
21,salient_verb,trabalhar,como um,cientista de dados,de vida que tal considerar,0.90,False,está procurando uma profissão que ofereça qual...
22,salient_verb,caiu,como uma,luva foi o Fransola,O vinho que,0.90,False,O vinho que caiu como uma luva foi o Fransola
23,salient_verb,caiu,como uma,bomba entre os ambientalistas,do Serviço Geológico do Brasil,0.90,False,A sugestão do Serviço Geológico do Brasil caiu...
24,salient_verb,caiu,como uma,luva apara mim,Nossa Marina esse seu posto,0.90,False,Nossa Marina… esse seu posto caiu como uma luv...
25,quality_adjective,duro,como uma,bolachanos aqui em casa adoramos,ele fica mais firmemas nao,0.90,False,do diferente mesmo em relação ao tempo.mas ao ...
26,salient_verb,cair,como um,raio sobre os responsáveis,estado colonial português apressou-se em,0.90,False,"alidade do europeu da época, por isso o estado..."
27,salient_verb,caiu,como uma,bomba no meu cérebro,A frase,0.90,False,A frase caiu como uma bomba no meu cérebro
28,salient_verb,voar,como um,simples pardal,nenhum homem consegue ao menos,0.90,False,aro quanto é certo que finda o homem e certo c...
29,salient_verb,trabalhar,como uma,estaca convencional,que a estaca não deverá,0.90,False,"nas a densificação do solo arenoso, isto é, co..."
30,salient_verb,trabalha,como um,verdadeiro CSI da vida real,de sistemas a computação forense,0.90,False,diz respeito à investigações legais e proteção...
31,salient_verb,caiu,como uma,luva na equipe japonesa,Stoner antes pois o australiano,0.90,False,star se perguntando o porquê não ter contratad...
32,quality_adjective,doce,como um,alimento nutritivo,nutricionistas estão recomendando a batata-,0.90,False,"andioca, em função do fato de que os nutricion..."
33,salient_verb,caiu,como uma,luva para o Ciganerey,sobre a Maria Bethânia que,0.90,False,"de Luizito, a Mangueira vai com tudo com esse ..."
34,quality_adjective,claro,como um,cinza claro,optar por um terno mais,0.90,False,"Jhon, pelo horário você pode optar por um tern..."
35,salient_verb,caiu,como uma,luva para mim,Sua resenha,0.90,False,Sua resenha caiu como uma luva para mim
36,quality_adjective,alto,como um,super heroi,já sonhou que estava voando,0.90,False,Se você já sonhou que estava voando alto como ...
37,salient_verb,cai,como uma,luva nos ambientes,A arte do design que,0.90,False,A arte do design que cai como uma luva nos amb...
38,quality_adjective,escura,como um,preto ou azul marinho,calça chino na tonalidade mais,0.90,False,uma vestimenta com tecido de Brin ou um modelo...
39,salient_verb,caiu,como uma,luva uma Audiobox USB,no meu caso na época,0.90,False,"( no meu caso na época, caiu como uma luva uma..."
40,quality_adjective,claras,como um,rosa leve,fora procure utilizar cores mais,0.90,False,Nas pinturas da parte de fora procure utilizar...
41,salient_verb,trabalhar,como um,verdadeiro mestre carpinteiro,completar essa tarefa você deverá,0.90,False,"oco colorido até o contorno correto, mas para ..."
42,salient_verb,cairia,como uma,luva noutro candidato,tão peculiares o apelido bicho-de-pé,0.90,False,"leria, disse que com essas características tão..."
43,salient_verb,cai,como uma,luva para o autônomo,A perícia judicial,0.90,False,A perícia judicial cai como uma luva para o au...
44,salient_verb,cairia,como uma,luva um Mojito,noite em pleno sábado bem,0.90,False,A estas horas da noite em pleno sábado bem cai...
45,salient_verb,caiu,como uma,bomba entre a gente,Isso,0.90,False,"""Isso caiu como uma bomba entre a gente"
46,salient_verb,brilhar,como uma,noiva esplêndida e inesquecível,realmente lindos que farão você,0.90,False,Nesta categoria há modelos realmente lindos qu...
47,salient_verb,correr,como um,coelho australiano,mais jovem e começa a,0.90,False,O pai se casa com uma mulher 39 anos mais jove...
48,quality_adjective,escuras,como um,marrom ou preto,dê preferência para tonalidades mais,0.90,False,"Evite também as botas com brilho, dê preferênc..."
49,salient_verb,caiu,como uma,luva para Aninha,O papel de Sookie Stackhouse,0.90,False,O papel de Sookie Stackhouse caiu como uma luv...