# Como-Article Ground/Vehicle MVP

Spec: `docs/specs/0006-como-article-ground-vehicle-mvp.md`

This is the canonical full-shard workflow for the current project. It uses a Spark-native prefilter before the Python extraction UDF, then writes the gold candidate dataset and compact analysis CSVs.

```text
Bronze corpus segments
  -> native Spark rlike prefilter for curated GROUND como article
  -> Python UDF extraction only on plausible rows
  -> gold Parquet and WebApp-ready CSV outputs
```

In [1]:
import os
from pathlib import Path
import sys

def find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "src/tal_qual").exists():
            return candidate
        if (candidate / "work/src/tal_qual").exists():
            return candidate / "work"
    raise RuntimeError(f"Could not find repository root from {start}")


REPO_ROOT = find_repo_root(Path.cwd())
os.chdir(REPO_ROOT)
SRC_DIR = REPO_ROOT / "src"
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

REPO_ROOT

PosixPath('/home/jovyan/work')

In [2]:
import os
import tempfile
import zipfile

from pyspark.sql import SparkSession

SPARK_MASTER = os.environ.get("TAL_QUAL_SPARK_MASTER", "local[4]")
SPARK_PARALLELISM = os.environ.get("TAL_QUAL_SPARK_PARALLELISM", "4")
SPARK_SHUFFLE_PARTITIONS = os.environ.get("TAL_QUAL_SPARK_SHUFFLE_PARTITIONS", "4")

spark = (
    SparkSession.builder
    .master(SPARK_MASTER)
    .appName("tal-qual-como-article-ground-vehicle-optimized-mvp")
    .config("spark.default.parallelism", SPARK_PARALLELISM)
    .config("spark.sql.shuffle.partitions", SPARK_SHUFFLE_PARTITIONS)
    .config("spark.sql.files.maxPartitionBytes", str(256 * 1024 * 1024))
    .config("spark.sql.adaptive.enabled", "true")
    .config("spark.sql.adaptive.coalescePartitions.enabled", "true")
    .getOrCreate()
)
spark.sparkContext.setLogLevel("WARN")

package_zip = Path(tempfile.gettempdir()) / "tal_qual_src.zip"
with zipfile.ZipFile(package_zip, "w", compression=zipfile.ZIP_DEFLATED) as archive:
    for file_path in sorted((SRC_DIR / "tal_qual").rglob("*.py")):
        archive.write(file_path, file_path.relative_to(SRC_DIR))

spark.sparkContext.addPyFile(str(package_zip))
SPARK_MASTER, spark.version

('local[4]', '4.1.1')

In [3]:
from tal_qual.bronze import BRONZE_OUTPUT_PATH, RAW_CORPUS_INPUT, load_or_build_bronze_dataframe
from tal_qual.como_article_ground_vehicle import (
    COMO_ARTICLE_EXAMPLES_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_VEHICLE_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_VEHICLE_OUTPUT_PATH,
    COMO_ARTICLE_REVIEW_SAMPLE_OUTPUT_PATH,
    COMO_ARTICLE_VEHICLE_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_VEHICLE_GROUND_COUNTS_OUTPUT_PATH,
    como_article_examples_dataframe,
    como_article_ground_counts_dataframe,
    como_article_ground_vehicle_counts_dataframe,
    como_article_review_sample_dataframe,
    como_article_vehicle_counts_dataframe,
    como_article_vehicle_ground_counts_dataframe,
    prefilter_como_article_ground_vehicle_bronze_dataframe,
    prepare_como_article_ground_vehicle_dataframe,
    write_como_article_csv_outputs,
    write_como_article_ground_vehicle_parquet,
)

## Load Or Build Bronze

The extractor expects the bronze schema from notebook 02. If bronze output is absent, this notebook builds it from the configured raw shard.

In [4]:
bronze_path = REPO_ROOT / os.environ.get("TAL_QUAL_BRONZE_PATH", str(BRONZE_OUTPUT_PATH))
raw_path = REPO_ROOT / os.environ.get("TAL_QUAL_RAW_CORPUS_INPUT", str(RAW_CORPUS_INPUT))

bronze_df = load_or_build_bronze_dataframe(spark, raw_path, bronze_path)

bronze_df.printSchema()

root
 |-- source_file: string (nullable = true)
 |-- original_line_id: long (nullable = true)
 |-- segment_id: integer (nullable = true)
 |-- text_original: string (nullable = true)
 |-- text_normalized: string (nullable = true)
 |-- match_text: string (nullable = true)

## Prefilter And Extract Spec-0006 Candidates

The native prefilter is intentionally broad but cheap. It reduces the number of rows sent through the Python UDF.

In [5]:
prefiltered_bronze_df = prefilter_como_article_ground_vehicle_bronze_dataframe(bronze_df).persist()
prefiltered_count = prefiltered_bronze_df.count()
print(f"Prefiltered bronze rows: {prefiltered_count:,}")

candidates_df = prepare_como_article_ground_vehicle_dataframe(prefiltered_bronze_df).persist()
candidate_count = candidates_df.count()
print(f"Spec-0006 candidates: {candidate_count:,}")
candidates_df

Prefiltered bronze rows: 333

/usr/local/spark/python/pyspark/sql/udf.py:134: UserWarning: Cannot infer the eval type from type hints.
  warnings.warn("Cannot infer the eval type from type hints. ", UserWarning)

Spec-0006 candidates: 204

DataFrame[candidate_id: string, source_file: string, original_line_id: bigint, segment_id: int, pattern_type: string, connector: string, connector_text: string, matched_text: string, candidate_full_text: string, text_before: string, tenor_text: string, tenor_lemma: string, tenor_confidence: string, ground_text: string, ground_lemma: string, ground_type: string, ground_source: string, vehicle_text: string, vehicle_lemma: string, vehicle_head: string, vehicle_head_lemma: string, vehicle_phrase_length_tokens: int, filter_label: string, reject_reason: string, confidence: double, needs_review: boolean, char_start: int, char_end: int, connector_start: int, connector_end: int, vehicle_start: int, vehicle_end: int]

In [6]:
candidates_df.printSchema()

root
 |-- candidate_id: string (nullable = true)
 |-- source_file: string (nullable = true)
 |-- original_line_id: long (nullable = true)
 |-- segment_id: integer (nullable = true)
 |-- pattern_type: string (nullable = true)
 |-- connector: string (nullable = true)
 |-- connector_text: string (nullable = true)
 |-- matched_text: string (nullable = true)
 |-- candidate_full_text: string (nullable = true)
 |-- text_before: string (nullable = true)
 |-- tenor_text: string (nullable = true)
 |-- tenor_lemma: string (nullable = true)
 |-- tenor_confidence: string (nullable = true)
 |-- ground_text: string (nullable = true)
 |-- ground_lemma: string (nullable = true)
 |-- ground_type: string (nullable = true)
 |-- ground_source: string (nullable = true)
 |-- vehicle_text: string (nullable = true)
 |-- vehicle_lemma: string (nullable = true)
 |-- vehicle_head: string (nullable = true)
 |-- vehicle_head_lemma: string (nullable = true)
 |-- vehicle_phrase_length_tokens: integer (nullable = true)
 |-- filter_label: string (nullable = true)
 |-- reject_reason: string (nullable = true)
 |-- confidence: double (nullable = true)
 |-- needs_review: boolean (nullable = true)
 |-- char_start: integer (nullable = true)
 |-- char_end: integer (nullable = true)
 |-- connector_start: integer (nullable = true)
 |-- connector_end: integer (nullable = true)
 |-- vehicle_start: integer (nullable = true)
 |-- vehicle_end: integer (nullable = true)

## Write Gold Dataset And Visualization CSVs

In [7]:
write_como_article_ground_vehicle_parquet(candidates_df, REPO_ROOT / COMO_ARTICLE_GROUND_VEHICLE_OUTPUT_PATH)
write_como_article_csv_outputs(
    candidates_df,
    ground_vehicle_counts_path=REPO_ROOT / COMO_ARTICLE_GROUND_VEHICLE_COUNTS_OUTPUT_PATH,
    vehicle_ground_counts_path=REPO_ROOT / COMO_ARTICLE_VEHICLE_GROUND_COUNTS_OUTPUT_PATH,
    ground_counts_path=REPO_ROOT / COMO_ARTICLE_GROUND_COUNTS_OUTPUT_PATH,
    vehicle_counts_path=REPO_ROOT / COMO_ARTICLE_VEHICLE_COUNTS_OUTPUT_PATH,
    examples_path=REPO_ROOT / COMO_ARTICLE_EXAMPLES_OUTPUT_PATH,
    review_sample_path=REPO_ROOT / COMO_ARTICLE_REVIEW_SAMPLE_OUTPUT_PATH,
)

## Inspect Visualization Tables

These displays use small materialized pandas tables for readability. The durable CSV outputs above remain the source of truth for downstream visualization work.

In [9]:
from pyspark.sql.functions import col

def display_table(spark_df, limit=30):
    display(spark_df.limit(limit).toPandas())


### Evaluation Strategy Outputs

In [10]:

print(f"Evaluation dataset: {EVALUATION_DATASET_PATH}")
print(f"Evaluation outputs: {EVALUATION_OUTPUT_ROOT}")
display_table(
    evaluation_df.groupBy("pattern_type").count().orderBy("pattern_type"),
    limit=20,
)

Evaluation dataset: data/gold/evaluation/como_article_strategy_candidates
Evaluation outputs: outputs/evaluation

                  pattern_type  count
0  como_article_ground_vehicle    204

### Ground -> Vehicle Pairs

In [11]:
display_table(
    como_article_ground_vehicle_counts_dataframe(candidates_df).select(
        col("ground_lemma").alias("ground"),
        col("vehicle_head_lemma").alias("vehicle_head"),
        "count",
    ),
    limit=40,
)

       ground vehicle_head  count
0        cair         luva     49
1        cair        bomba     24
2       forte        touro      4
3    assentar         luva      3
4       caber         luva      3
5    encaixar         luva      3
6     flutuar    borboleta      3
7      rápido       flecha      3
8      rápido         raio      3
9        cair   verdadeiro      2
10       cego      morcego      2
11  trabalhar      empresa      2
12  trabalhar   verdadeiro      2
13       voar        avião      2
14     alegre   passarinho      1
15       alto        caixa      1
16       alto      estrela      1
17       alto          pau      1
18       alto      pássaro      1
19       alto        super      1
20      baixo        barco      1
21      baixo       espaço      1
22      baixo         pipa      1
23      baixo        prego      1
24  brilhante        caixa      1
25  brilhante          luz      1
26    brilhar       centro      1
27    brilhar   gigantesco      1
28    brilhar         joia      1
29    brilhar        noiva      1
30       cair        aluva      1
31       cair      baralho      1
32       cair   castelinho      1
33       cair      patinha      1
34       cair      patinho      1
35       cair         raio      1
36       cair      simples      1
37       cair       trouxa      1
38      calmo        bomba      1
39      cheio          ovo      1

### Vehicle -> Ground Pairs

In [12]:
display_table(
    como_article_vehicle_ground_counts_dataframe(candidates_df).select(
        col("vehicle_head_lemma").alias("vehicle_head"),
        col("ground_lemma").alias("ground"),
        "count",
    ),
    limit=40,
)

   vehicle_head     ground  count
0          luva       cair     49
1         bomba       cair     24
2         touro      forte      4
3     borboleta    flutuar      3
4        flecha     rápido      3
5          luva   assentar      3
6          luva      caber      3
7          luva   encaixar      3
8          raio     rápido      3
9         avião       voar      2
10      empresa  trabalhar      2
11      morcego       cego      2
12   verdadeiro       cair      2
13   verdadeiro  trabalhar      2
14    aldebarán     rápido      1
15     alimento       doce      1
16        aluva       cair      1
17     amistoso     correr      1
18      artista  trabalhar      1
19     ativista  trabalhar      1
20     bacalhau       seco      1
21         bala     correr      1
22         bala    pequeno      1
23         bala     rápido      1
24      baralho       cair      1
25        barco      baixo      1
26    bicicleta    pequeno      1
27   bolachanos       duro      1
28        bomba      calmo      1
29        caixa       alto      1
30        caixa  brilhante      1
31     caminhão     grande      1
32     carvalho      forte      1
33      carícia       leve      1
34   castelinho       cair      1
35       cavalo      forte      1
36       cavalo     grande      1
37       centro    brilhar      1
38          chá     quente      1
39       cidade       duro      1

### Ground Counts

In [13]:
display_table(como_article_ground_counts_dataframe(candidates_df), limit=40)

   ground_lemma  count
0          cair     83
1     trabalhar     15
2         forte     12
3        rápido      9
4        correr      6
5          duro      6
6        grande      6
7          voar      6
8          alto      5
9      encaixar      5
10        baixo      4
11      brilhar      4
12      pequeno      4
13         seco      4
14     assentar      3
15        caber      3
16      flutuar      3
17         leve      3
18    brilhante      2
19         cego      2
20        claro      2
21         doce      2
22       escuro      2
23       frágil      2
24        livre      2
25       pesado      2
26       quente      2
27       alegre      1
28        calmo      1
29        cheio      1
30       triste      1
31        vazio      1

### Vehicle Counts

In [14]:
display_table(como_article_vehicle_counts_dataframe(candidates_df), limit=40)

                   pattern_type vehicle_head_clean  count
0   como_article_ground_vehicle               luva     58
1   como_article_ground_vehicle              bomba     25
2   como_article_ground_vehicle               raio      4
3   como_article_ground_vehicle              touro      4
4   como_article_ground_vehicle         verdadeiro      4
5   como_article_ground_vehicle               bala      3
6   como_article_ground_vehicle          borboleta      3
7   como_article_ground_vehicle             flecha      3
8   como_article_ground_vehicle              avião      2
9   como_article_ground_vehicle              caixa      2
10  como_article_ground_vehicle             cavalo      2
11  como_article_ground_vehicle              dente      2
12  como_article_ground_vehicle            empresa      2
13  como_article_ground_vehicle            morcego      2
14  como_article_ground_vehicle         passarinho      2
15  como_article_ground_vehicle              pedra      2
16  como_article_ground_vehicle              pluma      2
17  como_article_ground_vehicle            pássaro      2
18  como_article_ground_vehicle            simples      2
19  como_article_ground_vehicle          aldebarán      1
20  como_article_ground_vehicle           alimento      1
21  como_article_ground_vehicle              aluva      1
22  como_article_ground_vehicle           amistoso      1
23  como_article_ground_vehicle            artista      1
24  como_article_ground_vehicle           ativista      1
25  como_article_ground_vehicle           bacalhau      1
26  como_article_ground_vehicle            baralho      1
27  como_article_ground_vehicle              barco      1
28  como_article_ground_vehicle          bicicleta      1
29  como_article_ground_vehicle         bolachanos      1
30  como_article_ground_vehicle           caminhão      1
31  como_article_ground_vehicle           carvalho      1
32  como_article_ground_vehicle            carícia      1
33  como_article_ground_vehicle         castelinho      1
34  como_article_ground_vehicle             centro      1
35  como_article_ground_vehicle                chá      1
36  como_article_ground_vehicle             cidade      1
37  como_article_ground_vehicle          cientista      1
38  como_article_ground_vehicle              cinza      1
39  como_article_ground_vehicle             coelho      1

### Examples

In [15]:
display_table(
    como_article_examples_dataframe(candidates_df, limit=100).select(
        "ground_text",
        "connector_text",
        "vehicle_text",
        "tenor_text",
        "candidate_full_text",
    ),
    limit=50,
)

,pattern_type,ground_text,connector_text,vehicle_text_clean,candidate_full_text
0,como_article_ground_vehicle,alegre,como um,passarinho,"Ela abriu os olhos e saltou da cama, alegre co..."
1,como_article_ground_vehicle,alto,como uma,caixa,Para iniciar com tranqüilidade vamos sentar so...
2,como_article_ground_vehicle,alta,como uma,estrela,"gro vê-la, cego ser e não vê-la, eu preferira:..."
3,como_article_ground_vehicle,alta,como um,pau de sebo,"A criada, alta como um pau de sebo"
4,como_article_ground_vehicle,alto,como um,pássaro com asas de anjo,"Voarei além do céu, além das estrelas Voarei a..."
5,como_article_ground_vehicle,alto,como um,super heroi,Se você já sonhou que estava voando alto como ...
6,como_article_ground_vehicle,assenta,como uma,luva,"mundo tem lutado nasce da ideia de que ""o bem""..."
7,como_article_ground_vehicle,assenta,como uma,luva,Álvaro Magalhães é seguramente um daqueles a q...
8,como_article_ground_vehicle,assenta,como uma,luva no dia de hoje,"NA LISTA de livros que se pode ver [aqui], há ..."
9,como_article_ground_vehicle,baixo,como um,barco,empo eu supri minha sala com uma moderna répli...
10,como_article_ground_vehicle,baixo,como um,espaço de sala ou serviços,"ncia maior igual que 20m, é interessante aprov..."
11,como_article_ground_vehicle,baixo,como uma,pipa,"olveu tentar descobrir como era, se não voar c..."
12,como_article_ground_vehicle,baixo,como um,prego saindo de alguma madeira,Ouvi dizer que você não furar sua cabeça no Ja...
13,como_article_ground_vehicle,Brilhante,como uma,caixa de celofane âmbar,Brilhante como uma caixa de celofane âmbar
14,como_article_ground_vehicle,Brilhantes,como uma,luz,"ações!E quando chega o Natal,Levo a história d..."
15,como_article_ground_vehicle,brilhava,como um,centro planetário,"No meio da mesa, brilhava como um centro plane..."
16,como_article_ground_vehicle,brilhar,como um,gigantesco arco-íris repetitivo,Por que o céu haveria de brilhar como um gigan...
17,como_article_ground_vehicle,brilhar,como uma,joia,e apesar de todo o esforço não seja bem sucedi...
18,como_article_ground_vehicle,brilhar,como uma,noiva esplêndida e inesquecível,Nesta categoria há modelos realmente lindos qu...
19,como_article_ground_vehicle,cabe,como uma,luva,"renovada citação de Karl Marx - ""A história se..."
20,como_article_ground_vehicle,coube,como uma,luva,"MOELA DE AVESTRUZ 4O arremate, nesse caso, cou..."
21,como_article_ground_vehicle,cabe,como uma,luva,Chico Bondade é o personagem que lhe cabe como...
22,como_article_ground_vehicle,caiu,como um,aluva,"Ótimo texto, pra mim que pretendo ficar la um ..."
23,como_article_ground_vehicle,cair,como um,baralho de cartas,"rio, quando são feitas com mentiras e movidas ..."
24,como_article_ground_vehicle,caiu,como uma,bomba,Essa noticia caiu como uma bomba
25,como_article_ground_vehicle,cai,como uma,bomba,"Na tarde, cai como uma bomba"
26,como_article_ground_vehicle,caiu,como uma,bomba,"e mais emprega no RN e, uma das que gera mais ..."
27,como_article_ground_vehicle,caiu,como uma,bomba atômica nos meios políticos,A delação de Sérgio Machado caiu como uma bomb...
28,como_article_ground_vehicle,caiu,como uma,bomba na cidade,"ria aos secretários (à época, Charles Bacellar..."
29,como_article_ground_vehicle,caiu,como uma,bomba no meio político e,"A notícia, divulgada, ontem, à tarde, pelo Jor..."
30,como_article_ground_vehicle,cai,como uma,bomba no Planalto,idente participou das tratativas nada republic...
31,como_article_ground_vehicle,caiu,como uma,bomba entre os ambientalistas,A sugestão do Serviço Geológico do Brasil caiu...
32,como_article_ground_vehicle,caiu,como uma,bomba no meu cérebro,A frase caiu como uma bomba no meu cérebro
33,como_article_ground_vehicle,caiu,como uma,bomba,……………A mais recente pesquisa caiu como uma bomba
34,como_article_ground_vehicle,caiu,como uma,bomba entre a gente,"""Isso caiu como uma bomba entre a gente"
35,como_article_ground_vehicle,cai,como uma,bomba,"»Pensamos que isto só acontece aos outros, mas..."
36,como_article_ground_vehicle,caiu,como uma,bomba no meio da comunidade,O que poderia ter sido motivo para júbilo e co...
37,como_article_ground_vehicle,cairia,como uma,bomba para estas eleições,A união de Ronaldo e Belmiro cairia como uma b...
38,como_article_ground_vehicle,caiu,como uma,bomba no Heriberto Hulse,"que o Criciúma poderia perder pontos, conquist..."
39,como_article_ground_vehicle,caiu,como uma,bomba,elo final de tarde que a Rádio Macau deu a not...
40,como_article_ground_vehicle,caiu,como uma,bomba sobre o Centro Administrativo,"ra da Fazenda Pública, proibindo a veiculação ..."
41,como_article_ground_vehicle,caiu,como uma,bomba,A informação caiu como uma bomba
42,como_article_ground_vehicle,caiu,como uma,bomba,Aquela notícia me caiu como uma bomba
43,como_article_ground_vehicle,caiu,como uma,bomba,"Na época, isso caiu como uma bomba"
44,como_article_ground_vehicle,caiu,como uma,bomba em Búzios,A notícia da inelegibilidade por 10 anos do Ch...
45,como_article_ground_vehicle,caiu,como uma,bomba sem trocadilhos,"Na época, a reportagem caiu como uma bomba sem..."
46,como_article_ground_vehicle,caiu,como uma,bomba,A notícia caiu como uma bomba
47,como_article_ground_vehicle,caiu,como uma,bomba no mercado,Petrobras: dias ruins O balanço do terceiro tr...
48,como_article_ground_vehicle,caiu,como um,castelinho de areia,"ada tava numa boa com ele, viajando , fazendo ..."
49,como_article_ground_vehicle,caiu,como uma,luva,"Para a diretoria, o caso de Artur caiu como um..."

### Review Sample

In [16]:
display_table(
    como_article_review_sample_dataframe(candidates_df, limit=100).select(
        "ground_type",
        "ground_text",
        "connector_text",
        "vehicle_text",
        "tenor_text",
        "confidence",
        "needs_review",
        "candidate_full_text",
    ),
    limit=50,
)

,pattern_type,ground_text,connector_text,vehicle_text_clean,quality_reason,needs_review,candidate_full_text
0,como_article_ground_vehicle,Flutuar,como uma,borboleta,spec_0006_strict_filter,True,Flutuar como uma borboleta
1,como_article_ground_vehicle,Forte,como um,touro e alfabetizada,spec_0006_strict_filter,True,Forte como um touro e alfabetizada
2,como_article_ground_vehicle,Livre,como um,táxi,spec_0006_strict_filter,True,Livre como um táxi
3,como_article_ground_vehicle,Rápida,como uma,flecha,spec_0006_strict_filter,True,Rápida como uma flecha
4,como_article_ground_vehicle,Calmo,Como Uma,Bomba,spec_0006_strict_filter,True,Calmo Como Uma Bomba
5,como_article_ground_vehicle,Correu,como uma,bala para a pensão,spec_0006_strict_filter,True,Correu como uma bala para a pensão
6,como_article_ground_vehicle,Cego,como um,morcego,spec_0006_strict_filter,True,Cego como um morcego
7,como_article_ground_vehicle,Brilhante,como uma,caixa de celofane âmbar,spec_0006_strict_filter,True,Brilhante como uma caixa de celofane âmbar
8,como_article_ground_vehicle,voar,como um,avião,spec_0006_strict_filter,False,"a é bem sucedida, o módulo encontra a parte ma..."
9,como_article_ground_vehicle,caiu,como uma,bomba,spec_0006_strict_filter,False,Essa noticia caiu como uma bomba
10,como_article_ground_vehicle,trabalhar,como uma,empresa,spec_0006_strict_filter,False,"""O Sevilla não crescia até começar a trabalhar..."
11,como_article_ground_vehicle,cai,como uma,bomba,spec_0006_strict_filter,False,"Na tarde, cai como uma bomba"
12,como_article_ground_vehicle,baixo,como um,prego saindo de alguma madeira,spec_0006_strict_filter,False,Ouvi dizer que você não furar sua cabeça no Ja...
13,como_article_ground_vehicle,caiu,como uma,luva,spec_0006_strict_filter,False,"Para a diretoria, o caso de Artur caiu como um..."
14,como_article_ground_vehicle,caiu,como um,castelinho de areia,spec_0006_strict_filter,False,"ada tava numa boa com ele, viajando , fazendo ..."
15,como_article_ground_vehicle,cairia,como uma,luva,spec_0006_strict_filter,False,Meu comentário: um mecanismo desse em Maringá ...
16,como_article_ground_vehicle,alta,como uma,estrela,spec_0006_strict_filter,False,"gro vê-la, cego ser e não vê-la, eu preferira:..."
17,como_article_ground_vehicle,cai,como uma,luva para o papel,spec_0006_strict_filter,False,"[…] mundial dos vinhos, é interpretado por um ..."
18,como_article_ground_vehicle,fortes,como um,quintal de luxo,spec_0006_strict_filter,False,"e talvez seja: primeiro, combater a fome e a m..."
19,como_article_ground_vehicle,trabalhar,como um,artista de graffiti,spec_0006_strict_filter,False,"Na década de oitenta, ele começou a trabalhar ..."
20,como_article_ground_vehicle,correu,como um,amistoso,spec_0006_strict_filter,False,"o jogo já estava decidido, o Brasil e o Chile ..."
21,como_article_ground_vehicle,caiu,como uma,bomba,spec_0006_strict_filter,False,"e mais emprega no RN e, uma das que gera mais ..."
22,como_article_ground_vehicle,caiu,como uma,bomba atômica nos meios políticos,spec_0006_strict_filter,False,A delação de Sérgio Machado caiu como uma bomb...
23,como_article_ground_vehicle,caiu,como um,verdadeiro tsunami em Hollywood,spec_0006_strict_filter,False,A sueca caiu como um verdadeiro tsunami em Hol...
24,como_article_ground_vehicle,rápido,como um,raio,spec_0006_strict_filter,False,"De todo modo, o brilho jogado sobre Pence foi ..."
25,como_article_ground_vehicle,voar,como um,whirlydog,spec_0006_strict_filter,False,"parecer, como o Gato de ""Alice no País das Mar..."
26,como_article_ground_vehicle,cai,como uma,luva,spec_0006_strict_filter,False,os precisar de gente desqualificada para as es...
27,como_article_ground_vehicle,cabe,como uma,luva,spec_0006_strict_filter,False,"renovada citação de Karl Marx - ""A história se..."
28,como_article_ground_vehicle,cairia,como uma,luva,spec_0006_strict_filter,False,"tah totalmente em casa, manda muito no violão ..."
29,como_article_ground_vehicle,cega,como um,morcego,spec_0006_strict_filter,False,"expressão em inglês que diz que uma pessoa é ""..."
30,como_article_ground_vehicle,caiu,como uma,luva,spec_0006_strict_filter,False,Esse post caiu como uma luva
31,como_article_ground_vehicle,trabalhar,como uma,máquina,spec_0006_strict_filter,False,Enquanto você trabalhar como uma máquina
32,como_article_ground_vehicle,caiu,como uma,luva,spec_0006_strict_filter,False,essa faixa mopar caiu como uma luva
33,como_article_ground_vehicle,cheia,como um,ovo,spec_0006_strict_filter,False,"Na Catedral, quando cheia como um ovo"
34,como_article_ground_vehicle,seca,como um,forno,spec_0006_strict_filter,False,uas horas de trabalhos forçados não engolira u...
35,como_article_ground_vehicle,CAIR,COMO UMA,LUVA,spec_0006_strict_filter,False,"ma !!! Peço também, que ninguém, mas ninguém m..."
36,como_article_ground_vehicle,caiu,como uma,luva,spec_0006_strict_filter,False,"Como estamos sempre buscando o ""cálice sagrado..."
37,como_article_ground_vehicle,pesado,como uma,fragata a menos,spec_0006_strict_filter,False,tos mais atuais são de longuíssimo alcance ) e...
38,como_article_ground_vehicle,caiu,como uma,bomba na cidade,spec_0006_strict_filter,False,"ria aos secretários (à época, Charles Bacellar..."
39,como_article_ground_vehicle,livre,como um,passarinho,spec_0006_strict_filter,False,ostaria de saber se no início de um relacionam...
40,como_article_ground_vehicle,caiu,como uma,bomba no meio político e,spec_0006_strict_filter,False,"A notícia, divulgada, ontem, à tarde, pelo Jor..."
41,como_article_ground_vehicle,correu,como um,possuído na chuva,spec_0006_strict_filter,False,"Mais uma vez, o alemão da Toro Rosso correu co..."
42,como_article_ground_vehicle,rápido,como um,raio,spec_0006_strict_filter,False,A resoluta calma do artista incendiou o ânimo ...
43,como_article_ground_vehicle,cai,como uma,bomba no Planalto,spec_0006_strict_filter,False,idente participou das tratativas nada republic...
44,como_article_ground_vehicle,cai,como uma,luva no conceito de abnegação,spec_0006_strict_filter,False,"Logo, cai como uma luva no conceito de abnegação"
45,como_article_ground_vehicle,trabalhar,como um,cientista de dados,spec_0006_strict_filter,False,está procurando uma profissão que ofereça qual...
46,como_article_ground_vehicle,caiu,como uma,luva foi o Fransola,spec_0006_strict_filter,False,O vinho que caiu como uma luva foi o Fransola
47,como_article_ground_vehicle,encaixa,como uma,luva,spec_0006_strict_filter,False,stalar um montão de programas e coloca atalho ...
48,como_article_ground_vehicle,leve,como uma,carícia,spec_0006_strict_filter,False,Daí a pouco também ressonava com a respiração ...
49,como_article_ground_vehicle,duro,como um,kart,spec_0006_strict_filter,False,"Mineirim, o Santana não é duro como um kart"