# Como-Article Ground/Vehicle Full Corpus

Spec: `docs/specs/0006-como-article-ground-vehicle-mvp.md`

This notebook runs the same optimized extraction workflow as the single-shard MVP, but defaults to all local brWaC clean shards and a separate full-corpus bronze path so results can be compared without overwriting the baseline or half-corpus bronze datasets.

```text
Full-corpus bronze segments
  -> native Spark rlike prefilter for curated GROUND como article
  -> Python UDF extraction only on plausible rows
  -> gold Parquet and WebApp-ready CSV outputs
```

In [1]:
import os
from pathlib import Path
import sys

def find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "src/tal_qual").exists():
            return candidate
        if (candidate / "work/src/tal_qual").exists():
            return candidate / "work"
    raise RuntimeError(f"Could not find repository root from {start}")


REPO_ROOT = find_repo_root(Path.cwd())
os.chdir(REPO_ROOT)
SRC_DIR = REPO_ROOT / "src"
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

REPO_ROOT

PosixPath('/home/jovyan/work')

In [2]:
import os
import tempfile
import zipfile

from pyspark.sql import SparkSession

SPARK_MASTER = os.environ.get("TAL_QUAL_SPARK_MASTER", "local[4]")
SPARK_PARALLELISM = os.environ.get("TAL_QUAL_SPARK_PARALLELISM", "4")
SPARK_SHUFFLE_PARTITIONS = os.environ.get("TAL_QUAL_SPARK_SHUFFLE_PARTITIONS", "4")

spark = (
    SparkSession.builder
    .master(SPARK_MASTER)
    .appName("tal-qual-como-article-ground-vehicle-full-corpus")
    .config("spark.default.parallelism", SPARK_PARALLELISM)
    .config("spark.sql.shuffle.partitions", SPARK_SHUFFLE_PARTITIONS)
    .config("spark.sql.files.maxPartitionBytes", str(256 * 1024 * 1024))
    .config("spark.sql.adaptive.enabled", "true")
    .config("spark.sql.adaptive.coalescePartitions.enabled", "true")
    .getOrCreate()
)
spark.sparkContext.setLogLevel("WARN")

package_zip = Path(tempfile.gettempdir()) / "tal_qual_src.zip"
with zipfile.ZipFile(package_zip, "w", compression=zipfile.ZIP_DEFLATED) as archive:
    for file_path in sorted((SRC_DIR / "tal_qual").rglob("*.py")):
        archive.write(file_path, file_path.relative_to(SRC_DIR))

spark.sparkContext.addPyFile(str(package_zip))
SPARK_MASTER, spark.version

('local[4]', '4.1.1')

In [3]:
from tal_qual.bronze import BRONZE_OUTPUT_PATH, RAW_CORPUS_INPUT, load_or_build_bronze_dataframe
from tal_qual.como_article_ground_vehicle import (
    COMO_ARTICLE_EXAMPLES_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_VEHICLE_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_VEHICLE_OUTPUT_PATH,
    COMO_ARTICLE_REVIEW_SAMPLE_OUTPUT_PATH,
    COMO_ARTICLE_VEHICLE_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_VEHICLE_GROUND_COUNTS_OUTPUT_PATH,
    como_article_examples_dataframe,
    como_article_ground_counts_dataframe,
    como_article_ground_vehicle_counts_dataframe,
    como_article_review_sample_dataframe,
    como_article_vehicle_counts_dataframe,
    como_article_vehicle_ground_counts_dataframe,
    prefilter_como_article_ground_vehicle_bronze_dataframe,
    prepare_como_article_ground_vehicle_dataframe,
    write_como_article_csv_outputs,
    write_como_article_ground_vehicle_parquet,
)

## Load Or Build Bronze

The extractor expects the bronze schema from notebook 02. If bronze output is absent, this notebook builds it from the configured raw shard.

In [4]:
FULL_CORPUS_RAW_INPUT = "data/raw/brwac-clean-*.txt.gz"
FULL_CORPUS_BRONZE_PATH = "data/bronze/brwac_segments_full"

bronze_path = REPO_ROOT / os.environ.get("TAL_QUAL_BRONZE_PATH", FULL_CORPUS_BRONZE_PATH)
raw_path = REPO_ROOT / os.environ.get("TAL_QUAL_RAW_CORPUS_INPUT", FULL_CORPUS_RAW_INPUT)

bronze_df = load_or_build_bronze_dataframe(spark, raw_path, bronze_path)

print(f"Raw input: {raw_path}")
print(f"Bronze path: {bronze_path}")
bronze_df.select("source_file").distinct().orderBy("source_file").show(20, truncate=False)

bronze_df.printSchema()

Raw input: /home/jovyan/work/data/raw/brwac-clean-*.txt.gz
Bronze path: /home/jovyan/work/data/bronze/brwac_segments_full
+-------------------------------------------------------+
|source_file                                            |
+-------------------------------------------------------+
|file:///home/jovyan/work/data/raw/brwac-clean-1.txt.gz |
|file:///home/jovyan/work/data/raw/brwac-clean-10.txt.gz|
|file:///home/jovyan/work/data/raw/brwac-clean-11.txt.gz|
|file:///home/jovyan/work/data/raw/brwac-clean-12.txt.gz|
|file:///home/jovyan/work/data/raw/brwac-clean-2.txt.gz |
|file:///home/jovyan/work/data/raw/brwac-clean-3.txt.gz |
|file:///home/jovyan/work/data/raw/brwac-clean-4.txt.gz |
|file:///home/jovyan/work/data/raw/brwac-clean-5.txt.gz |
|file:///home/jovyan/work/data/raw/brwac-clean-6.txt.gz |
|file:///home/jovyan/work/data/raw/brwac-clean-7.txt.gz |
|file:///home/jovyan/work/data/raw/brwac-clean-8.txt.gz |
|file:///home/jovyan/work/data/raw/brwac-clean-9.txt.gz |
+-------------------------------------------------------+

root
 |-- source_file: string (nullable = true)
 |-- original_line_id: long (nullable = true)
 |-- segment_id: integer (nullable = true)
 |-- text_original: string (nullable = true)
 |-- text_normalized: string (nullable = true)
 |-- match_text: string (nullable = true)

## Prefilter And Extract Spec-0006 Candidates

The native prefilter is intentionally broad but cheap. It reduces the number of rows sent through the Python UDF.

In [5]:
prefiltered_bronze_df = prefilter_como_article_ground_vehicle_bronze_dataframe(bronze_df).persist()
prefiltered_count = prefiltered_bronze_df.count()
print(f"Prefiltered bronze rows: {prefiltered_count:,}")

candidates_df = prepare_como_article_ground_vehicle_dataframe(prefiltered_bronze_df).persist()
candidate_count = candidates_df.count()
print(f"Spec-0006 candidates: {candidate_count:,}")
candidates_df

Prefiltered bronze rows: 3,524

/usr/local/spark/python/pyspark/sql/udf.py:134: UserWarning: Cannot infer the eval type from type hints.
  warnings.warn("Cannot infer the eval type from type hints. ", UserWarning)

Spec-0006 candidates: 2,136

DataFrame[candidate_id: string, source_file: string, original_line_id: bigint, segment_id: int, pattern_type: string, connector: string, connector_text: string, matched_text: string, candidate_full_text: string, text_before: string, tenor_text: string, tenor_lemma: string, tenor_confidence: string, ground_text: string, ground_lemma: string, ground_type: string, ground_source: string, vehicle_text: string, vehicle_lemma: string, vehicle_head: string, vehicle_head_lemma: string, vehicle_phrase_length_tokens: int, filter_label: string, reject_reason: string, confidence: double, needs_review: boolean, char_start: int, char_end: int, connector_start: int, connector_end: int, vehicle_start: int, vehicle_end: int]

In [6]:
candidates_df.printSchema()

root
 |-- candidate_id: string (nullable = true)
 |-- source_file: string (nullable = true)
 |-- original_line_id: long (nullable = true)
 |-- segment_id: integer (nullable = true)
 |-- pattern_type: string (nullable = true)
 |-- connector: string (nullable = true)
 |-- connector_text: string (nullable = true)
 |-- matched_text: string (nullable = true)
 |-- candidate_full_text: string (nullable = true)
 |-- text_before: string (nullable = true)
 |-- tenor_text: string (nullable = true)
 |-- tenor_lemma: string (nullable = true)
 |-- tenor_confidence: string (nullable = true)
 |-- ground_text: string (nullable = true)
 |-- ground_lemma: string (nullable = true)
 |-- ground_type: string (nullable = true)
 |-- ground_source: string (nullable = true)
 |-- vehicle_text: string (nullable = true)
 |-- vehicle_lemma: string (nullable = true)
 |-- vehicle_head: string (nullable = true)
 |-- vehicle_head_lemma: string (nullable = true)
 |-- vehicle_phrase_length_tokens: integer (nullable = true)
 |-- filter_label: string (nullable = true)
 |-- reject_reason: string (nullable = true)
 |-- confidence: double (nullable = true)
 |-- needs_review: boolean (nullable = true)
 |-- char_start: integer (nullable = true)
 |-- char_end: integer (nullable = true)
 |-- connector_start: integer (nullable = true)
 |-- connector_end: integer (nullable = true)
 |-- vehicle_start: integer (nullable = true)
 |-- vehicle_end: integer (nullable = true)

## Write Gold Dataset And Visualization CSVs

In [7]:
write_como_article_ground_vehicle_parquet(candidates_df, REPO_ROOT / COMO_ARTICLE_GROUND_VEHICLE_OUTPUT_PATH)
write_como_article_csv_outputs(
    candidates_df,
    ground_vehicle_counts_path=REPO_ROOT / COMO_ARTICLE_GROUND_VEHICLE_COUNTS_OUTPUT_PATH,
    vehicle_ground_counts_path=REPO_ROOT / COMO_ARTICLE_VEHICLE_GROUND_COUNTS_OUTPUT_PATH,
    ground_counts_path=REPO_ROOT / COMO_ARTICLE_GROUND_COUNTS_OUTPUT_PATH,
    vehicle_counts_path=REPO_ROOT / COMO_ARTICLE_VEHICLE_COUNTS_OUTPUT_PATH,
    examples_path=REPO_ROOT / COMO_ARTICLE_EXAMPLES_OUTPUT_PATH,
    review_sample_path=REPO_ROOT / COMO_ARTICLE_REVIEW_SAMPLE_OUTPUT_PATH,
)

## Inspect Visualization Tables

These displays use small materialized pandas tables for readability. The durable CSV outputs above remain the source of truth for downstream visualization work.

In [9]:
from pyspark.sql.functions import col

def display_table(spark_df, limit=30):
    display(spark_df.limit(limit).toPandas())


### Evaluation Strategy Outputs

In [10]:

print(f"Evaluation dataset: {EVALUATION_DATASET_PATH}")
print(f"Evaluation outputs: {EVALUATION_OUTPUT_ROOT}")
display_table(
    evaluation_df.groupBy("pattern_type").count().orderBy("pattern_type"),
    limit=20,
)

Evaluation dataset: data/gold/evaluation/como_article_strategy_candidates
Evaluation outputs: outputs/evaluation

                  pattern_type  count
0  como_article_ground_vehicle   2136

### Ground -> Vehicle Pairs

In [11]:
display_table(
    como_article_ground_vehicle_counts_dataframe(candidates_df).select(
        col("ground_lemma").alias("ground"),
        col("vehicle_head_lemma").alias("vehicle_head"),
        "count",
    ),
    limit=40,
)

       ground vehicle_head  count
0        cair         luva    452
1        cair        bomba    208
2    encaixar         luva     37
3       caber         luva     25
4        duro        pedra     25
5        leve        pluma     21
6      rápido         raio     20
7    assentar         luva     19
8        duro        rocha     17
9       forte        touro     17
10      livre      pássaro     16
11       cair         raio     15
12       voar      pássaro     12
13       leve         pena     11
14     rápido       flecha     11
15   assentar       rainha     10
16       cair      patinho     10
17      forte        rocha     10
18      forte     ventania     10
19       voar        avião     10
20       cair      castelo      9
21  trabalhar       equipe      9
22    brilhar      estrela      8
23    brilhar      tesouro      7
24     correr        doido      7
25     correr        galgo      7
26      cheio          ovo      6
27     correr         xara      6
28    flutuar    borboleta      6
29      livre   passarinho      6
30     pesado     elefante      6
31  trabalhar         time      6
32      baixo    vira-lata      5
33    brilhar        farol      5
34       cair        pedra      5
35     correr          rio      5
36  trabalhar      escravo      5
37  trabalhar        mouro      5
38       voar        águia      5
39      claro          dia      4

### Vehicle -> Ground Pairs

In [12]:
display_table(
    como_article_vehicle_ground_counts_dataframe(candidates_df).select(
        col("vehicle_head_lemma").alias("vehicle_head"),
        col("ground_lemma").alias("ground"),
        "count",
    ),
    limit=40,
)

   vehicle_head     ground  count
0          luva       cair    452
1         bomba       cair    208
2          luva   encaixar     37
3          luva      caber     25
4         pedra       duro     25
5         pluma       leve     21
6          raio     rápido     20
7          luva   assentar     19
8         rocha       duro     17
9         touro      forte     17
10      pássaro      livre     16
11         raio       cair     15
12      pássaro       voar     12
13       flecha     rápido     11
14         pena       leve     11
15        avião       voar     10
16      patinho       cair     10
17       rainha   assentar     10
18        rocha      forte     10
19     ventania      forte     10
20      castelo       cair      9
21       equipe  trabalhar      9
22      estrela    brilhar      8
23        doido     correr      7
24        galgo     correr      7
25      tesouro    brilhar      7
26    borboleta    flutuar      6
27     elefante     pesado      6
28          ovo      cheio      6
29   passarinho      livre      6
30         time  trabalhar      6
31         xara     correr      6
32      escravo  trabalhar      5
33        farol    brilhar      5
34        mouro  trabalhar      5
35        pedra       cair      5
36          rio     correr      5
37    vira-lata      baixo      5
38        águia       voar      5
39         bala     rápido      4

### Ground Counts

In [13]:
display_table(como_article_ground_counts_dataframe(candidates_df), limit=40)

   ground_lemma  count
0          cair    783
1     trabalhar    167
2         forte     97
3          duro     83
4        rápido     82
5        correr     70
6          leve     70
7        grande     64
8       brilhar     61
9      encaixar     52
10        livre     50
11         voar     49
12      pequeno     35
13        claro     34
14         alto     33
15     assentar     32
16         frio     32
17         seco     29
18        caber     28
19         doce     28
20        baixo     23
21       frágil     23
22        preso     20
23       escuro     19
24       alegre     18
25    brilhante     18
26       quente     18
27       pesado     16
28        vazio     13
29        calmo     12
30        cheio     12
31       triste     12
32      flutuar     10
33        limpo     10
34        lento      9
35         sujo      7
36        fraco      6
37       amargo      4
38         mole      4
39         cego      3

### Vehicle Counts

In [14]:
display_table(como_article_vehicle_counts_dataframe(candidates_df), limit=40)

                   pattern_type vehicle_head_clean  count
0   como_article_ground_vehicle               luva    533
1   como_article_ground_vehicle              bomba    210
2   como_article_ground_vehicle               raio     38
3   como_article_ground_vehicle              pedra     35
4   como_article_ground_vehicle            pássaro     34
5   como_article_ground_vehicle              rocha     29
6   como_article_ground_vehicle              pluma     22
7   como_article_ground_vehicle              touro     18
8   como_article_ground_vehicle             flecha     14
9   como_article_ground_vehicle          borboleta     13
10  como_article_ground_vehicle            estrela     12
11  como_article_ground_vehicle               pena     12
12  como_article_ground_vehicle              avião     11
13  como_article_ground_vehicle            castelo     10
14  como_article_ground_vehicle             equipe     10
15  como_article_ground_vehicle            patinho     10
16  como_article_ground_vehicle             rainha     10
17  como_article_ground_vehicle           ventania     10
18  como_article_ground_vehicle           elefante      9
19  como_article_ground_vehicle                rio      9
20  como_article_ground_vehicle            criança      8
21  como_article_ground_vehicle              doido      8
22  como_article_ground_vehicle            tesouro      8
23  como_article_ground_vehicle               bala      7
24  como_article_ground_vehicle                dia      7
25  como_article_ground_vehicle              galgo      7
26  como_article_ground_vehicle         passarinho      7
27  como_article_ground_vehicle               time      7
28  como_article_ground_vehicle         verdadeiro      7
29  como_article_ground_vehicle              águia      7
30  como_article_ground_vehicle                bom      6
31  como_article_ground_vehicle             cavalo      6
32  como_article_ground_vehicle              farol      6
33  como_article_ground_vehicle              homem      6
34  como_article_ground_vehicle              louco      6
35  como_article_ground_vehicle                ovo      6
36  como_article_ground_vehicle          relâmpago      6
37  como_article_ground_vehicle               xara      6
38  como_article_ground_vehicle           diamante      5
39  como_article_ground_vehicle            escravo      5

### Examples

In [15]:
display_table(
    como_article_examples_dataframe(candidates_df, limit=100).select(
        "ground_text",
        "connector_text",
        "vehicle_text",
        "tenor_text",
        "candidate_full_text",
    ),
    limit=50,
)

,pattern_type,ground_text,connector_text,vehicle_text_clean,candidate_full_text
0,como_article_ground_vehicle,Alegre,como uma,alternativa ao pós-Socrates,Eu não olho para Manuel Alegre como uma altern...
1,como_article_ground_vehicle,alegre,como uma,amiga minha,"u quero ir a Paris, tomar uns ""banhos"" e volta..."
2,como_article_ground_vehicle,Alegre,como um,caçador ou arranjador de votos,"a, criativa, produtora de nova realidade, que ..."
3,como_article_ground_vehicle,Alegre,como uma,cidade conectada,As imagens apresentam o cotidiano de Porto Ale...
4,como_article_ground_vehicle,alegre,como uma,criança,Saí da jaula dos filhotes de leões alegre como...
5,como_article_ground_vehicle,alegre,como uma,criança ao ter comprado,"epois passa-me a nostalgia, pois só o discerni..."
6,como_article_ground_vehicle,alegre,como um,galo,", e, por ter ela crescido, em tão estranhos «v..."
7,como_article_ground_vehicle,alegre,como um,horto de flores,- Vila Viçosa é alegre como um horto de flores
8,como_article_ground_vehicle,alegre,como uma,manhã de abril,"Malvina, que vinha do interior da casa, risonh..."
9,como_article_ground_vehicle,Alegre,como um,modelo internacional,ferência internacional em políticas sociais e ...
10,como_article_ground_vehicle,alegre,como um,moço,Ao comtemplar o seu retrato parece-me ainda vé...
11,como_article_ground_vehicle,alegre,como um,palhaço,"er Pan, esperança de Dickens, sonhador como Do..."
12,como_article_ground_vehicle,alegre,como um,palhaço,"er Pan, esperança de Dickens, sonhador como Do..."
13,como_article_ground_vehicle,alegre,como um,palhaço,"er Pan, esperança de Dickens, sonhador como Do..."
14,como_article_ground_vehicle,alegre,como um,pardal depois da chuva,Regressei á cidade alegre como um pardal depoi...
15,como_article_ground_vehicle,alegre,como um,passarinho,"Ela abriu os olhos e saltou da cama, alegre co..."
16,como_article_ground_vehicle,alegre,como um,rio,Eu era alegre como um rio
17,como_article_ground_vehicle,alegre,como uma,romaria e pequenino mas tesinho,"Apesar de ser "" alegre como uma romaria e pequ..."
18,como_article_ground_vehicle,alto,como um,automóvel 0km,"o era muita, mas sempre faz a diferença na hor..."
19,como_article_ground_vehicle,alto,como um,bolo de noiva,Catherine chegou para seu primeiro encontro co...
20,como_article_ground_vehicle,alto,como um,box fixo,"enjoar da estampa, é só trocar por outra ainda..."
21,como_article_ground_vehicle,alto,como uma,cadeira,"erfil de uma bruxa cavalgando uma vassoura, pi..."
22,como_article_ground_vehicle,alto,como uma,caixa,Para iniciar com tranqüilidade vamos sentar so...
23,como_article_ground_vehicle,alto,como uma,danadaa c,calor e eu que tenho de ir à outra casa buscar...
24,como_article_ground_vehicle,altos,como um,dia quis Ícaro,os bibliotecários de Babel que se comoviam com...
25,como_article_ground_vehicle,alto,como uma,dolorosa bandeira,"o mar Aqui, neste fragmento de África onde, vi..."
26,como_article_ground_vehicle,alta,como um,edif cio de sete andares,Os problemas em torno das obras dessa monument...
27,como_article_ground_vehicle,alta,como um,edifício de sete andares,Os problemas em torno das obras dessa monument...
28,como_article_ground_vehicle,alta,como uma,estrela,"gro vê-la, cego ser e não vê-la, eu preferira:..."
29,como_article_ground_vehicle,alto,como uma,frutose,"Eu fui, alto como uma frutose"
30,como_article_ground_vehicle,alto,como um,homem,"mesmo horário, com a mesma posição do Sol sobr..."
31,como_article_ground_vehicle,alto,como um,homem Cabeça erguida,m isso de novo•Então aqueles são meus sonhos•E...
32,como_article_ground_vehicle,alto,como uma,minivan,"O Fit pode ter a carroceria de monovolume, mas..."
33,como_article_ground_vehicle,alta,como uma,oração,"do a se juntarem a mim nesse exacto momento, e..."
34,como_article_ground_vehicle,alta,como um,pau de sebo,"A criada, alta como um pau de sebo"
35,como_article_ground_vehicle,alto,como um,pinheiro,"Então de repente o Casco cresceu todo, no soli..."
36,como_article_ground_vehicle,alto,como uma,piranha,A pornografia freqüentemente rotula a mulher d...
37,como_article_ground_vehicle,alta,como uma,planta kala jovem,Lá mora sua rainha Vimala com um corpo qual tr...
38,como_article_ground_vehicle,alto,como um,porco sendo castrado e desabou,"Quando o cacique contou o ocorrido, Luiz Perei..."
39,como_article_ground_vehicle,alto,como um,poste,I24 sobre o congresso do PS vê-se repetidament...
40,como_article_ground_vehicle,alta,como um,prédio de uns três andares,"ell Douglas C-124 Globemaster II, um quadrimot..."
41,como_article_ground_vehicle,alto,como um,pássaro com asas de anjo,"Voarei além do céu, além das estrelas Voarei a..."
42,como_article_ground_vehicle,alto,como um,pássaro,ói de nada Só quero a companhia de outros braç...
43,como_article_ground_vehicle,alta,como uma,reprimenda de pai,— Não quero ver suas fotos! — Minha voz é afia...
44,como_article_ground_vehicle,altos,como um,sinal perigoso,"Até recentemente , os médicos não consideram t..."
45,como_article_ground_vehicle,alto,como uma,sirene de ambulância,Acordo com o som do meu despertador berrando r...
46,como_article_ground_vehicle,alto,como um,super heroi,Se você já sonhou que estava voando alto como ...
47,como_article_ground_vehicle,alto,como uma,torre,"ego: um homem (sim, claro, de cabelos e pele d..."
48,como_article_ground_vehicle,alta,como um,tuiuiú,Ela queria muito ser alta como um tuiuiú
49,como_article_ground_vehicle,alta,como uma,árvore mãe,Ela se erguia alta como uma árvore mãe

### Review Sample

In [16]:
display_table(
    como_article_review_sample_dataframe(candidates_df, limit=100).select(
        "ground_type",
        "ground_text",
        "connector_text",
        "vehicle_text",
        "tenor_text",
        "confidence",
        "needs_review",
        "candidate_full_text",
    ),
    limit=50,
)

,pattern_type,ground_text,connector_text,vehicle_text_clean,quality_reason,needs_review,candidate_full_text
0,como_article_ground_vehicle,Mole,como uma,carne de sol,spec_0006_strict_filter,True,Mole como uma carne de sol
1,como_article_ground_vehicle,Pesado,como um,elefante luz,spec_0006_strict_filter,True,Pesado como um elefante luz
2,como_article_ground_vehicle,Caiu,como uma,luva,spec_0006_strict_filter,True,Caiu como uma luva
3,como_article_ground_vehicle,Correu,como um,rastilho de pólvora,spec_0006_strict_filter,True,Correu como um rastilho de pólvora
4,como_article_ground_vehicle,Caiu,como uma,luva,spec_0006_strict_filter,True,Caiu como uma luva
5,como_article_ground_vehicle,Grande,como um,continente,spec_0006_strict_filter,True,Grande como um continente
6,como_article_ground_vehicle,Trabalhar,como uma,aranha,spec_0006_strict_filter,True,Trabalhar como uma aranha
7,como_article_ground_vehicle,Pequeno,como um,tostão,spec_0006_strict_filter,True,Pequeno como um tostão
8,como_article_ground_vehicle,Rápido,como uma,raposa,spec_0006_strict_filter,True,Rápido como uma raposa
9,como_article_ground_vehicle,Correu,como uma,bala para a pensão,spec_0006_strict_filter,True,Correu como uma bala para a pensão
10,como_article_ground_vehicle,Flutue,como uma,borboleta,spec_0006_strict_filter,True,Flutue como uma borboleta
11,como_article_ground_vehicle,Livre,como um,pássaro,spec_0006_strict_filter,True,Livre como um pássaro
12,como_article_ground_vehicle,Leve,como uma,pluma,spec_0006_strict_filter,True,Leve como uma pluma
13,como_article_ground_vehicle,Rápido,como um,raio,spec_0006_strict_filter,True,Rápido como um raio
14,como_article_ground_vehicle,Livre,como um,pássaro,spec_0006_strict_filter,True,Livre como um pássaro
15,como_article_ground_vehicle,Rápido,como um,raio,spec_0006_strict_filter,True,Rápido como um raio
16,como_article_ground_vehicle,Frio,como um,peixe,spec_0006_strict_filter,True,Frio como um peixe
17,como_article_ground_vehicle,Rápido,como um,piloto deve ser,spec_0006_strict_filter,True,Rápido como um piloto deve ser
18,como_article_ground_vehicle,caiu,como uma,luva,spec_0006_strict_filter,True,caiu como uma luva
19,como_article_ground_vehicle,Caiu,como uma,bomba,spec_0006_strict_filter,True,Caiu como uma bomba
20,como_article_ground_vehicle,brilhar,como um,farol,spec_0006_strict_filter,True,brilhar como um farol
21,como_article_ground_vehicle,Livre,como um,pássaro,spec_0006_strict_filter,True,Livre como um pássaro
22,como_article_ground_vehicle,Livre,como um,táxi de madrugada na Paulista,spec_0006_strict_filter,True,Livre como um táxi de madrugada na Paulista
23,como_article_ground_vehicle,Leve,como um,robe de cetim no verão,spec_0006_strict_filter,True,Leve como um robe de cetim no verão
24,como_article_ground_vehicle,CAIU,COMO UMA,LUVA PRA MIM ESSE POST,spec_0006_strict_filter,True,CAIU COMO UMA LUVA PRA MIM ESSE POST
25,como_article_ground_vehicle,Forte,como um,touro,spec_0006_strict_filter,True,Forte como um touro
26,como_article_ground_vehicle,Livre,como um,pássaro,spec_0006_strict_filter,True,Livre como um pássaro
27,como_article_ground_vehicle,Livre,Como Um,Deus,spec_0006_strict_filter,True,Livre Como Um Deus
28,como_article_ground_vehicle,Rápido,como um,clique,spec_0006_strict_filter,True,Rápido como um clique
29,como_article_ground_vehicle,Cego,como um,morcego,spec_0006_strict_filter,True,Cego como um morcego
30,como_article_ground_vehicle,Leve,como um,automóvel,spec_0006_strict_filter,True,Leve como um automóvel
31,como_article_ground_vehicle,Brilhar,como um,farol,spec_0006_strict_filter,True,Brilhar como um farol
32,como_article_ground_vehicle,Rápido,como um,relâmpago,spec_0006_strict_filter,True,Rápido como um relâmpago
33,como_article_ground_vehicle,Forte,como uma,ventania,spec_0006_strict_filter,True,Forte como uma ventania
34,como_article_ground_vehicle,livre,como uma,ave,spec_0006_strict_filter,True,livre como uma ave
35,como_article_ground_vehicle,Caiu,como uma,luva,spec_0006_strict_filter,True,Caiu como uma luva
36,como_article_ground_vehicle,Rápida,como uma,flecha,spec_0006_strict_filter,True,Rápida como uma flecha
37,como_article_ground_vehicle,Cheia,como um,ovo,spec_0006_strict_filter,True,Cheia como um ovo
38,como_article_ground_vehicle,Caiu,como uma,luva,spec_0006_strict_filter,True,Caiu como uma luva
39,como_article_ground_vehicle,Caiu,como uma,luva,spec_0006_strict_filter,True,Caiu como uma luva
40,como_article_ground_vehicle,Brilhante,como uma,caixa de celofane âmbar,spec_0006_strict_filter,True,Brilhante como uma caixa de celofane âmbar
41,como_article_ground_vehicle,Leve,como uma,pluma,spec_0006_strict_filter,True,Leve como uma pluma
42,como_article_ground_vehicle,Forte,como um,touro,spec_0006_strict_filter,True,Forte como um touro
43,como_article_ground_vehicle,Rápido,como uma,Perestroika,spec_0006_strict_filter,True,Rápido como uma Perestroika
44,como_article_ground_vehicle,Encaixa,como uma,Luva,spec_0006_strict_filter,True,Encaixa como uma Luva
45,como_article_ground_vehicle,Rápido,como um,esquilo,spec_0006_strict_filter,True,Rápido como um esquilo
46,como_article_ground_vehicle,Cair,como um,pato,spec_0006_strict_filter,True,Cair como um pato
47,como_article_ground_vehicle,Dura,como uma,Absolut,spec_0006_strict_filter,True,Dura como uma Absolut
48,como_article_ground_vehicle,Voa,Como Um,Falcão escreveu,spec_0006_strict_filter,True,Voa Como Um Falcão escreveu
49,como_article_ground_vehicle,Frágil,como uma,flor,spec_0006_strict_filter,True,Frágil como uma flor