# Como-Article Ground/Vehicle Half-Corpus

Spec: `docs/specs/0006-como-article-ground-vehicle-mvp.md`

This notebook runs the same optimized extraction workflow as the single-shard MVP, but defaults to brWaC shards 1-6 and a separate half-corpus bronze path so results can be compared without overwriting the baseline bronze dataset.

```text
Half-corpus bronze segments
  -> native Spark rlike prefilter for curated GROUND como article
  -> Python UDF extraction only on plausible rows
  -> gold Parquet and WebApp-ready CSV outputs
```

In [1]:
import os
from pathlib import Path
import sys

def find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "src/tal_qual").exists():
            return candidate
        if (candidate / "work/src/tal_qual").exists():
            return candidate / "work"
    raise RuntimeError(f"Could not find repository root from {start}")


REPO_ROOT = find_repo_root(Path.cwd())
os.chdir(REPO_ROOT)
SRC_DIR = REPO_ROOT / "src"
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

REPO_ROOT

PosixPath('/home/jovyan/work')

In [2]:
import os
import tempfile
import zipfile

from pyspark.sql import SparkSession

SPARK_MASTER = os.environ.get("TAL_QUAL_SPARK_MASTER", "local[4]")
SPARK_PARALLELISM = os.environ.get("TAL_QUAL_SPARK_PARALLELISM", "4")
SPARK_SHUFFLE_PARTITIONS = os.environ.get("TAL_QUAL_SPARK_SHUFFLE_PARTITIONS", "4")

spark = (
    SparkSession.builder
    .master(SPARK_MASTER)
    .appName("tal-qual-como-article-ground-vehicle-half-corpus")
    .config("spark.default.parallelism", SPARK_PARALLELISM)
    .config("spark.sql.shuffle.partitions", SPARK_SHUFFLE_PARTITIONS)
    .config("spark.sql.files.maxPartitionBytes", str(256 * 1024 * 1024))
    .config("spark.sql.adaptive.enabled", "true")
    .config("spark.sql.adaptive.coalescePartitions.enabled", "true")
    .getOrCreate()
)
spark.sparkContext.setLogLevel("WARN")

package_zip = Path(tempfile.gettempdir()) / "tal_qual_src.zip"
with zipfile.ZipFile(package_zip, "w", compression=zipfile.ZIP_DEFLATED) as archive:
    for file_path in sorted((SRC_DIR / "tal_qual").rglob("*.py")):
        archive.write(file_path, file_path.relative_to(SRC_DIR))

spark.sparkContext.addPyFile(str(package_zip))
SPARK_MASTER, spark.version

('local[4]', '4.1.1')

In [3]:
from tal_qual.bronze import BRONZE_OUTPUT_PATH, RAW_CORPUS_INPUT, load_or_build_bronze_dataframe
from tal_qual.como_article_ground_vehicle import (
    COMO_ARTICLE_EXAMPLES_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_VEHICLE_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_GROUND_VEHICLE_OUTPUT_PATH,
    COMO_ARTICLE_REVIEW_SAMPLE_OUTPUT_PATH,
    COMO_ARTICLE_VEHICLE_COUNTS_OUTPUT_PATH,
    COMO_ARTICLE_VEHICLE_GROUND_COUNTS_OUTPUT_PATH,
    como_article_examples_dataframe,
    como_article_ground_counts_dataframe,
    como_article_ground_vehicle_counts_dataframe,
    como_article_review_sample_dataframe,
    como_article_vehicle_counts_dataframe,
    como_article_vehicle_ground_counts_dataframe,
    prefilter_como_article_ground_vehicle_bronze_dataframe,
    prepare_como_article_ground_vehicle_dataframe,
    write_como_article_csv_outputs,
    write_como_article_ground_vehicle_parquet,
)

## Load Or Build Bronze

The extractor expects the bronze schema from notebook 02. If bronze output is absent, this notebook builds it from the configured raw shard.

In [4]:
HALF_CORPUS_RAW_INPUT = "data/raw/brwac-clean-[1-6].txt.gz"
HALF_CORPUS_BRONZE_PATH = "data/bronze/brwac_segments_half"

bronze_path = REPO_ROOT / os.environ.get("TAL_QUAL_BRONZE_PATH", HALF_CORPUS_BRONZE_PATH)
raw_path = REPO_ROOT / os.environ.get("TAL_QUAL_RAW_CORPUS_INPUT", HALF_CORPUS_RAW_INPUT)

bronze_df = load_or_build_bronze_dataframe(spark, raw_path, bronze_path)

print(f"Raw input: {raw_path}")
print(f"Bronze path: {bronze_path}")
bronze_df.select("source_file").distinct().orderBy("source_file").show(truncate=False)

bronze_df.printSchema()

Raw input: /home/jovyan/work/data/raw/brwac-clean-[1-6].txt.gz
Bronze path: /home/jovyan/work/data/bronze/brwac_segments_half
+------------------------------------------------------+
|source_file                                           |
+------------------------------------------------------+
|file:///home/jovyan/work/data/raw/brwac-clean-1.txt.gz|
|file:///home/jovyan/work/data/raw/brwac-clean-2.txt.gz|
|file:///home/jovyan/work/data/raw/brwac-clean-3.txt.gz|
|file:///home/jovyan/work/data/raw/brwac-clean-4.txt.gz|
|file:///home/jovyan/work/data/raw/brwac-clean-5.txt.gz|
|file:///home/jovyan/work/data/raw/brwac-clean-6.txt.gz|
+------------------------------------------------------+

root
 |-- source_file: string (nullable = true)
 |-- original_line_id: long (nullable = true)
 |-- segment_id: integer (nullable = true)
 |-- text_original: string (nullable = true)
 |-- text_normalized: string (nullable = true)
 |-- match_text: string (nullable = true)

## Prefilter And Extract Spec-0006 Candidates

The native prefilter is intentionally broad but cheap. It reduces the number of rows sent through the Python UDF.

In [5]:
prefiltered_bronze_df = prefilter_como_article_ground_vehicle_bronze_dataframe(bronze_df).persist()
prefiltered_count = prefiltered_bronze_df.count()
print(f"Prefiltered bronze rows: {prefiltered_count:,}")

candidates_df = prepare_como_article_ground_vehicle_dataframe(prefiltered_bronze_df).persist()
candidate_count = candidates_df.count()
print(f"Spec-0006 candidates: {candidate_count:,}")
candidates_df

Prefiltered bronze rows: 1,819

/usr/local/spark/python/pyspark/sql/udf.py:134: UserWarning: Cannot infer the eval type from type hints.
  warnings.warn("Cannot infer the eval type from type hints. ", UserWarning)

Spec-0006 candidates: 1,080

DataFrame[candidate_id: string, source_file: string, original_line_id: bigint, segment_id: int, pattern_type: string, connector: string, connector_text: string, matched_text: string, candidate_full_text: string, text_before: string, tenor_text: string, tenor_lemma: string, tenor_confidence: string, ground_text: string, ground_lemma: string, ground_type: string, ground_source: string, vehicle_text: string, vehicle_lemma: string, vehicle_head: string, vehicle_head_lemma: string, vehicle_phrase_length_tokens: int, filter_label: string, reject_reason: string, confidence: double, needs_review: boolean, char_start: int, char_end: int, connector_start: int, connector_end: int, vehicle_start: int, vehicle_end: int]

In [6]:
candidates_df.printSchema()

root
 |-- candidate_id: string (nullable = true)
 |-- source_file: string (nullable = true)
 |-- original_line_id: long (nullable = true)
 |-- segment_id: integer (nullable = true)
 |-- pattern_type: string (nullable = true)
 |-- connector: string (nullable = true)
 |-- connector_text: string (nullable = true)
 |-- matched_text: string (nullable = true)
 |-- candidate_full_text: string (nullable = true)
 |-- text_before: string (nullable = true)
 |-- tenor_text: string (nullable = true)
 |-- tenor_lemma: string (nullable = true)
 |-- tenor_confidence: string (nullable = true)
 |-- ground_text: string (nullable = true)
 |-- ground_lemma: string (nullable = true)
 |-- ground_type: string (nullable = true)
 |-- ground_source: string (nullable = true)
 |-- vehicle_text: string (nullable = true)
 |-- vehicle_lemma: string (nullable = true)
 |-- vehicle_head: string (nullable = true)
 |-- vehicle_head_lemma: string (nullable = true)
 |-- vehicle_phrase_length_tokens: integer (nullable = true)
 |-- filter_label: string (nullable = true)
 |-- reject_reason: string (nullable = true)
 |-- confidence: double (nullable = true)
 |-- needs_review: boolean (nullable = true)
 |-- char_start: integer (nullable = true)
 |-- char_end: integer (nullable = true)
 |-- connector_start: integer (nullable = true)
 |-- connector_end: integer (nullable = true)
 |-- vehicle_start: integer (nullable = true)
 |-- vehicle_end: integer (nullable = true)

## Write Gold Dataset And Visualization CSVs

In [7]:
write_como_article_ground_vehicle_parquet(candidates_df, REPO_ROOT / COMO_ARTICLE_GROUND_VEHICLE_OUTPUT_PATH)
write_como_article_csv_outputs(
    candidates_df,
    ground_vehicle_counts_path=REPO_ROOT / COMO_ARTICLE_GROUND_VEHICLE_COUNTS_OUTPUT_PATH,
    vehicle_ground_counts_path=REPO_ROOT / COMO_ARTICLE_VEHICLE_GROUND_COUNTS_OUTPUT_PATH,
    ground_counts_path=REPO_ROOT / COMO_ARTICLE_GROUND_COUNTS_OUTPUT_PATH,
    vehicle_counts_path=REPO_ROOT / COMO_ARTICLE_VEHICLE_COUNTS_OUTPUT_PATH,
    examples_path=REPO_ROOT / COMO_ARTICLE_EXAMPLES_OUTPUT_PATH,
    review_sample_path=REPO_ROOT / COMO_ARTICLE_REVIEW_SAMPLE_OUTPUT_PATH,
)

## Inspect Visualization Tables

These displays use small materialized pandas tables for readability. The durable CSV outputs above remain the source of truth for downstream visualization work.

In [9]:
from pyspark.sql.functions import col

def display_table(spark_df, limit=30):
    display(spark_df.limit(limit).toPandas())


### Evaluation Strategy Outputs

In [10]:

print(f"Evaluation dataset: {EVALUATION_DATASET_PATH}")
print(f"Evaluation outputs: {EVALUATION_OUTPUT_ROOT}")
display_table(
    evaluation_df.groupBy("pattern_type").count().orderBy("pattern_type"),
    limit=20,
)

Evaluation dataset: data/gold/evaluation/como_article_strategy_candidates
Evaluation outputs: outputs/evaluation

                  pattern_type  count
0  como_article_ground_vehicle   1080

### Ground -> Vehicle Pairs

In [11]:
display_table(
    como_article_ground_vehicle_counts_dataframe(candidates_df).select(
        col("ground_lemma").alias("ground"),
        col("vehicle_head_lemma").alias("vehicle_head"),
        "count",
    ),
    limit=40,
)

       ground  vehicle_head  count
0        cair          luva    245
1        cair         bomba    107
2       caber          luva     16
3        duro         pedra     14
4    encaixar          luva     13
5      rápido          raio     11
6    assentar          luva     10
7       livre       pássaro     10
8        leve         pluma      8
9        duro         rocha      7
10      forte         touro      7
11       voar         avião      7
12     rápido        flecha      6
13  trabalhar        equipe      6
14    brilhar       estrela      5
15    brilhar       tesouro      5
16      forte         rocha      5
17       leve          pena      5
18     pesado      elefante      5
19   assentar        rainha      4
20       cair       patinho      4
21       cair          raio      4
22      forte      ventania      4
23      livre    passarinho      4
24      livre          táxi      4
25       voar       pássaro      4
26    brilhar         farol      3
27       cair       castelo      3
28       cair         pedra      3
29      cheio           ovo      3
30      claro           dia      3
31     correr           rio      3
32    flutuar     borboleta      3
33       leve     plumanada      3
34  trabalhar       empresa      3
35  trabalhar       escravo      3
36  trabalhar         homem      3
37  trabalhar  profissional      3
38  trabalhar          time      3
39     alegre       criança      2

### Vehicle -> Ground Pairs

In [12]:
display_table(
    como_article_vehicle_ground_counts_dataframe(candidates_df).select(
        col("vehicle_head_lemma").alias("vehicle_head"),
        col("ground_lemma").alias("ground"),
        "count",
    ),
    limit=40,
)

    vehicle_head     ground  count
0           luva       cair    245
1          bomba       cair    107
2           luva      caber     16
3          pedra       duro     14
4           luva   encaixar     13
5           raio     rápido     11
6           luva   assentar     10
7        pássaro      livre     10
8          pluma       leve      8
9          avião       voar      7
10         rocha       duro      7
11         touro      forte      7
12        equipe  trabalhar      6
13        flecha     rápido      6
14      elefante     pesado      5
15       estrela    brilhar      5
16          pena       leve      5
17         rocha      forte      5
18       tesouro    brilhar      5
19    passarinho      livre      4
20       patinho       cair      4
21       pássaro       voar      4
22        rainha   assentar      4
23          raio       cair      4
24          táxi      livre      4
25      ventania      forte      4
26     borboleta    flutuar      3
27       castelo       cair      3
28           dia      claro      3
29       empresa  trabalhar      3
30       escravo  trabalhar      3
31         farol    brilhar      3
32         homem  trabalhar      3
33           ovo      cheio      3
34         pedra       cair      3
35     plumanada       leve      3
36  profissional  trabalhar      3
37           rio     correr      3
38          time  trabalhar      3
39        abraço     quente      2

### Ground Counts

In [13]:
display_table(como_article_ground_counts_dataframe(candidates_df), limit=40)

   ground_lemma  count
0          cair    414
1     trabalhar     80
2        rápido     43
3          duro     42
4         forte     42
5       brilhar     34
6          leve     30
7        grande     29
8         livre     28
9        correr     24
10         voar     23
11     encaixar     22
12        claro     21
13         frio     20
14         seco     20
15         alto     19
16        caber     18
17      pequeno     17
18     assentar     14
19    brilhante     13
20        baixo     11
21       escuro     11
22       frágil     11
23       pesado     11
24        preso     10
25       alegre      9
26        vazio      9
27         doce      8
28       quente      8
29        cheio      6
30      flutuar      6
31        limpo      6
32        calmo      5
33        lento      4
34       amargo      3
35         sujo      3
36       triste      3
37         cego      2
38         mole      1

### Vehicle Counts

In [14]:
display_table(como_article_vehicle_counts_dataframe(candidates_df), limit=40)

                   pattern_type vehicle_head_clean  count
0   como_article_ground_vehicle               luva    284
1   como_article_ground_vehicle              bomba    108
2   como_article_ground_vehicle              pedra     20
3   como_article_ground_vehicle            pássaro     18
4   como_article_ground_vehicle               raio     16
5   como_article_ground_vehicle              rocha     14
6   como_article_ground_vehicle              pluma      9
7   como_article_ground_vehicle              avião      8
8   como_article_ground_vehicle            estrela      8
9   como_article_ground_vehicle             flecha      8
10  como_article_ground_vehicle              touro      8
11  como_article_ground_vehicle          borboleta      6
12  como_article_ground_vehicle           elefante      6
13  como_article_ground_vehicle             equipe      6
14  como_article_ground_vehicle                rio      6
15  como_article_ground_vehicle               bala      5
16  como_article_ground_vehicle                dia      5
17  como_article_ground_vehicle              homem      5
18  como_article_ground_vehicle         passarinho      5
19  como_article_ground_vehicle               pena      5
20  como_article_ground_vehicle            tesouro      5
21  como_article_ground_vehicle         verdadeiro      5
22  como_article_ground_vehicle            castelo      4
23  como_article_ground_vehicle            criança      4
24  como_article_ground_vehicle              farol      4
25  como_article_ground_vehicle              folha      4
26  como_article_ground_vehicle            patinho      4
27  como_article_ground_vehicle             rainha      4
28  como_article_ground_vehicle               táxi      4
29  como_article_ground_vehicle           ventania      4
30  como_article_ground_vehicle        alternativa      3
31  como_article_ground_vehicle              balão      3
32  como_article_ground_vehicle              barco      3
33  como_article_ground_vehicle             cavalo      3
34  como_article_ground_vehicle            cristal      3
35  como_article_ground_vehicle           diamante      3
36  como_article_ground_vehicle            empresa      3
37  como_article_ground_vehicle            escravo      3
38  como_article_ground_vehicle              louco      3
39  como_article_ground_vehicle              manhã      3

### Examples

In [15]:
display_table(
    como_article_examples_dataframe(candidates_df, limit=100).select(
        "ground_text",
        "connector_text",
        "vehicle_text",
        "tenor_text",
        "candidate_full_text",
    ),
    limit=50,
)

,pattern_type,ground_text,connector_text,vehicle_text_clean,candidate_full_text
0,como_article_ground_vehicle,Alegre,como uma,alternativa ao pós-Socrates,Eu não olho para Manuel Alegre como uma altern...
1,como_article_ground_vehicle,alegre,como uma,criança ao ter comprado,"epois passa-me a nostalgia, pois só o discerni..."
2,como_article_ground_vehicle,alegre,como uma,criança,Saí da jaula dos filhotes de leões alegre como...
3,como_article_ground_vehicle,alegre,como um,galo,", e, por ter ela crescido, em tão estranhos «v..."
4,como_article_ground_vehicle,alegre,como uma,manhã de abril,"Malvina, que vinha do interior da casa, risonh..."
5,como_article_ground_vehicle,Alegre,como um,modelo internacional,ferência internacional em políticas sociais e ...
6,como_article_ground_vehicle,alegre,como um,palhaço,"er Pan, esperança de Dickens, sonhador como Do..."
7,como_article_ground_vehicle,alegre,como um,passarinho,"Ela abriu os olhos e saltou da cama, alegre co..."
8,como_article_ground_vehicle,alegre,como um,rio,Eu era alegre como um rio
9,como_article_ground_vehicle,alto,como um,automóvel 0km,"o era muita, mas sempre faz a diferença na hor..."
10,como_article_ground_vehicle,alto,como um,bolo de noiva,Catherine chegou para seu primeiro encontro co...
11,como_article_ground_vehicle,alto,como uma,cadeira,"erfil de uma bruxa cavalgando uma vassoura, pi..."
12,como_article_ground_vehicle,alto,como uma,caixa,Para iniciar com tranqüilidade vamos sentar so...
13,como_article_ground_vehicle,alta,como um,edif cio de sete andares,Os problemas em torno das obras dessa monument...
14,como_article_ground_vehicle,alta,como um,edifício de sete andares,Os problemas em torno das obras dessa monument...
15,como_article_ground_vehicle,alta,como uma,estrela,"gro vê-la, cego ser e não vê-la, eu preferira:..."
16,como_article_ground_vehicle,alto,como um,homem Cabeça erguida,m isso de novo•Então aqueles são meus sonhos•E...
17,como_article_ground_vehicle,alta,como uma,oração,"do a se juntarem a mim nesse exacto momento, e..."
18,como_article_ground_vehicle,alta,como um,pau de sebo,"A criada, alta como um pau de sebo"
19,como_article_ground_vehicle,alto,como um,pinheiro,"Então de repente o Casco cresceu todo, no soli..."
20,como_article_ground_vehicle,alto,como uma,piranha,A pornografia freqüentemente rotula a mulher d...
21,como_article_ground_vehicle,alto,como um,porco sendo castrado e desabou,"Quando o cacique contou o ocorrido, Luiz Perei..."
22,como_article_ground_vehicle,alto,como um,poste,I24 sobre o congresso do PS vê-se repetidament...
23,como_article_ground_vehicle,alto,como um,pássaro com asas de anjo,"Voarei além do céu, além das estrelas Voarei a..."
24,como_article_ground_vehicle,alto,como um,pássaro,ói de nada Só quero a companhia de outros braç...
25,como_article_ground_vehicle,alto,como uma,sirene de ambulância,Acordo com o som do meu despertador berrando r...
26,como_article_ground_vehicle,alto,como um,super heroi,Se você já sonhou que estava voando alto como ...
27,como_article_ground_vehicle,alto,como uma,torre,"ego: um homem (sim, claro, de cabelos e pele d..."
28,como_article_ground_vehicle,amargo,como um,aliado Mais uma vez,Pessoas com tendência a sofrerem eventos cardi...
29,como_article_ground_vehicle,amargo,como um,aliado,podem ter o chocolate amargo como um aliado
30,como_article_ground_vehicle,amargo,como um,bitter,"Como eu disse anteriormente, no início o elixi..."
31,como_article_ground_vehicle,assenta,como uma,luva,"mundo tem lutado nasce da ideia de que ""o bem""..."
32,como_article_ground_vehicle,assentou,como uma,luva,"ema do Brecht, adaptou-o para uma bela letra c..."
33,como_article_ground_vehicle,assenta,como uma,luva no dia de hoje,"NA LISTA de livros que se pode ver [aqui], há ..."
34,como_article_ground_vehicle,assenta,como uma,luva e a que Portugal,iança das Civilizações pelo Secretário-geral d...
35,como_article_ground_vehicle,assenta,como uma,luva,ro Histórico precioso de tão bonito e que ir s...
36,como_article_ground_vehicle,assenta,como uma,luva,Álvaro Magalhães é seguramente um daqueles a q...
37,como_article_ground_vehicle,assenta,como uma,luva,entusiasmo de que a Argentina fizesse parte do...
38,como_article_ground_vehicle,assenta,como uma,luva à actual situação alemã,Esta maravilhosa tirada do agora cómico ex vic...
39,como_article_ground_vehicle,assenta,como uma,luva,e lhe assenta tão bem - «acho que são ambos bo...
40,como_article_ground_vehicle,assenta,como uma,luva em Luis Filipe Vieira,Por isso é que a escolha de Luis Bernardo asse...
41,como_article_ground_vehicle,assentou,como uma,rainha Ez,"rael – Capitulo 156 do blog-1), e com isso, Je..."
42,como_article_ground_vehicle,ASSENTOU,COMO UMA,RAINHA,aqui em Ezequiel 16-13 vemos que Jerusalém rec...
43,como_article_ground_vehicle,ASSENTOU,COMO UMA,RAINHA,"esma coisa de APOCALIPSE 18-7, onde vemos que ..."
44,como_article_ground_vehicle,assentou,como uma,rainha Ezequiel 16-13,ulo 156 do blog-1: www.sabiosentenderao.blogsp...
45,como_article_ground_vehicle,baixo,como um,anão,"nstra no comando do time da CBF, mas será uma ..."
46,como_article_ground_vehicle,baixo,como um,barco,empo eu supri minha sala com uma moderna répli...
47,como_article_ground_vehicle,baixo,Como uma,cachoeira,"Eu acerto uma parede, nunca me senti tão para ..."
48,como_article_ground_vehicle,baixo,como um,espaço de sala ou serviços,"ncia maior igual que 20m, é interessante aprov..."
49,como_article_ground_vehicle,baixos,como um,esportivo tem que ser,sempenho sem apelar pra motores turbo ou motor...

### Review Sample

In [16]:
display_table(
    como_article_review_sample_dataframe(candidates_df, limit=100).select(
        "ground_type",
        "ground_text",
        "connector_text",
        "vehicle_text",
        "tenor_text",
        "confidence",
        "needs_review",
        "candidate_full_text",
    ),
    limit=50,
)

,pattern_type,ground_text,connector_text,vehicle_text_clean,quality_reason,needs_review,candidate_full_text
0,como_article_ground_vehicle,Encaixa,como uma,Luva,spec_0006_strict_filter,True,Encaixa como uma Luva
1,como_article_ground_vehicle,Brilhar,como um,farol,spec_0006_strict_filter,True,Brilhar como um farol
2,como_article_ground_vehicle,Grande,como um,continente,spec_0006_strict_filter,True,Grande como um continente
3,como_article_ground_vehicle,Flutuar,como uma,borboleta,spec_0006_strict_filter,True,Flutuar como uma borboleta
4,como_article_ground_vehicle,Trabalhar,como uma,aranha,spec_0006_strict_filter,True,Trabalhar como uma aranha
5,como_article_ground_vehicle,Caiu,como uma,luva,spec_0006_strict_filter,True,Caiu como uma luva
6,como_article_ground_vehicle,Livre,Como Um,Deus,spec_0006_strict_filter,True,Livre Como Um Deus
7,como_article_ground_vehicle,Rápida,como uma,flecha,spec_0006_strict_filter,True,Rápida como uma flecha
8,como_article_ground_vehicle,Livre,como um,táxi,spec_0006_strict_filter,True,Livre como um táxi
9,como_article_ground_vehicle,Livre,como um,táxi de madrugada na Paulista,spec_0006_strict_filter,True,Livre como um táxi de madrugada na Paulista
10,como_article_ground_vehicle,Rápido,como uma,Perestroika,spec_0006_strict_filter,True,Rápido como uma Perestroika
11,como_article_ground_vehicle,Livre,como um,pássaro,spec_0006_strict_filter,True,Livre como um pássaro
12,como_article_ground_vehicle,Pesado,como um,elefante luz,spec_0006_strict_filter,True,Pesado como um elefante luz
13,como_article_ground_vehicle,Caiu,como uma,luva,spec_0006_strict_filter,True,Caiu como uma luva
14,como_article_ground_vehicle,Cego,como um,morcego,spec_0006_strict_filter,True,Cego como um morcego
15,como_article_ground_vehicle,Forte,como um,touro e alfabetizada,spec_0006_strict_filter,True,Forte como um touro e alfabetizada
16,como_article_ground_vehicle,brilhar,como um,farol,spec_0006_strict_filter,True,brilhar como um farol
17,como_article_ground_vehicle,Livre,como um,pássaro,spec_0006_strict_filter,True,Livre como um pássaro
18,como_article_ground_vehicle,Brilhante,como uma,caixa de celofane âmbar,spec_0006_strict_filter,True,Brilhante como uma caixa de celofane âmbar
19,como_article_ground_vehicle,Livre,como um,pássaro,spec_0006_strict_filter,True,Livre como um pássaro
20,como_article_ground_vehicle,Rápido,como um,clique,spec_0006_strict_filter,True,Rápido como um clique
21,como_article_ground_vehicle,Leve,como um,automóvel,spec_0006_strict_filter,True,Leve como um automóvel
22,como_article_ground_vehicle,Frio,como um,peixe,spec_0006_strict_filter,True,Frio como um peixe
23,como_article_ground_vehicle,Caiu,como uma,luva,spec_0006_strict_filter,True,Caiu como uma luva
24,como_article_ground_vehicle,Forte,como um,touro,spec_0006_strict_filter,True,Forte como um touro
25,como_article_ground_vehicle,Cair,como um,pato,spec_0006_strict_filter,True,Cair como um pato
26,como_article_ground_vehicle,Dura,como uma,Absolut,spec_0006_strict_filter,True,Dura como uma Absolut
27,como_article_ground_vehicle,Leve,como uma,pena,spec_0006_strict_filter,True,Leve como uma pena
28,como_article_ground_vehicle,Rápida,como uma,seta,spec_0006_strict_filter,True,Rápida como uma seta
29,como_article_ground_vehicle,Livre,Como Um,Pássaro Beatles Tradução,spec_0006_strict_filter,True,Livre Como Um Pássaro Beatles Tradução
30,como_article_ground_vehicle,Calmo,Como Uma,Bomba,spec_0006_strict_filter,True,Calmo Como Uma Bomba
31,como_article_ground_vehicle,Forte,como um,esportivo,spec_0006_strict_filter,True,Forte como um esportivo
32,como_article_ground_vehicle,Correu,como uma,bala para a pensão,spec_0006_strict_filter,True,Correu como uma bala para a pensão
33,como_article_ground_vehicle,cair,como uma,bomba,spec_0006_strict_filter,False,vai cair como uma bomba
34,como_article_ground_vehicle,alto,como um,pássaro com asas de anjo,spec_0006_strict_filter,False,"Voarei além do céu, além das estrelas Voarei a..."
35,como_article_ground_vehicle,cair,como uma,luva,spec_0006_strict_filter,False,"nesa de contar histórias em quadrinhos, Free M..."
36,como_article_ground_vehicle,cabe,como uma,luva para tantos outros,spec_0006_strict_filter,False,"inimigos os rigores da lei!""? – de atribuição ..."
37,como_article_ground_vehicle,caiu,como um,patinho na conversa do amado,spec_0006_strict_filter,False,"Apesar de ser tão esperta, Diana caiu como um ..."
38,como_article_ground_vehicle,trabalha,como um,verdadeiro CSI da vida real,spec_0006_strict_filter,False,diz respeito à investigações legais e proteção...
39,como_article_ground_vehicle,Clara,como uma,vilã,spec_0006_strict_filter,False,Você definiria a Clara como uma vilã
40,como_article_ground_vehicle,cair,como uma,luva rústica,spec_0006_strict_filter,False,Para as mães adeptas do estilo simples e natur...
41,como_article_ground_vehicle,grande,como um,subgênero de filmes,spec_0006_strict_filter,False,maiores exemplos de como uma ideia criativa e ...
42,como_article_ground_vehicle,caiu,como uma,luva,spec_0006_strict_filter,False,essa faixa mopar caiu como uma luva
43,como_article_ground_vehicle,trabalhar,como uma,estaca convencional,spec_0006_strict_filter,False,"nas a densificação do solo arenoso, isto é, co..."
44,como_article_ground_vehicle,caiu,como uma,luva nos UT,spec_0006_strict_filter,False,"belíssima cor, caiu como uma luva nos UT"
45,como_article_ground_vehicle,caiu,como uma,bomba,spec_0006_strict_filter,False,Aquela notícia me caiu como uma bomba
46,como_article_ground_vehicle,assenta,como uma,luva,spec_0006_strict_filter,False,"mundo tem lutado nasce da ideia de que ""o bem""..."
47,como_article_ground_vehicle,caiu,como uma,luva,spec_0006_strict_filter,False,"Para a diretoria, o caso de Artur caiu como um..."
48,como_article_ground_vehicle,caiu,como um,dominó,spec_0006_strict_filter,False,Uma Pessoa Não Nomeada veio me contar o causo ...
49,como_article_ground_vehicle,coube,como uma,luva,spec_0006_strict_filter,False,"de esôfago, no Einstein, que tem vocação em pr..."